# Generated by Django 5.2.14 on 2026-05-14 16:51

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DqaRule",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("rule_id", models.CharField(db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("blocking", "Blocking"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=16,
                    ),
                ),
                ("applicability_filter", models.JSONField(blank=True, default=dict)),
                ("expression", models.JSONField()),
                ("error_message_template", models.CharField(max_length=256)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending approval"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("author", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DQA rule",
                "verbose_name_plural": "DQA rules",
                "indexes": [
                    models.Index(
                        fields=["status", "rule_id"],
                        name="dqa_dqarule_status_d079ac_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="dqa_dqarule_severit_60ce1a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule_id", "version"), name="dqarule_id_version_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DqaResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type", models.CharField(max_length=64)),
                ("record_id", models.CharField(max_length=64)),
                ("passed", models.BooleanField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("blocking", "Blocking"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="dqa.dqarule",
                    ),
                ),
            ],
            options={
                "verbose_name": "DQA result",
                "verbose_name_plural": "DQA results",
                "indexes": [
                    models.Index(
                        fields=["record_type", "record_id"],
                        name="dqa_dqaresu_record__8f8f10_idx",
                    ),
                    models.Index(
                        fields=["rule", "executed_at"],
                        name="dqa_dqaresu_rule_id_6d7bc7_idx",
                    ),
                    models.Index(
                        fields=["passed", "severity"],
                        name="dqa_dqaresu_passed_eb561b_idx",
                    ),
                ],
            },
        ),
    ]
