# Generated by Django 5.2.14 on 2026-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dqa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dqarule",
            name="approval_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dqarule",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dqarule",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
