# Generated by Django 5.2.14 on 2026-05-16 12:43

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dqa", "0002_lifecycle_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DqaRulePreviewRun",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("sample_size", models.PositiveIntegerField()),
                ("record_type", models.CharField(max_length=32)),
                ("pass_count", models.PositiveIntegerField()),
                ("fail_count", models.PositiveIntegerField()),
                (
                    "sample_failed_record_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("executed_by", models.CharField(max_length=64)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preview_runs",
                        to="dqa.dqarule",
                    ),
                ),
            ],
            options={
                "verbose_name": "DQA rule preview run",
                "verbose_name_plural": "DQA rule preview runs",
                "indexes": [
                    models.Index(
                        fields=["rule", "-executed_at"],
                        name="dqa_dqarule_rule_id_c9c9a2_idx",
                    )
                ],
            },
        ),
    ]
