# Generated by Django 5.2.17 on 2026-09-22 20:40

from django.db import migrations, models


def retire_superseded_actives(apps, schema_editor):
    """Retire every ACTIVE version but the highest, per rule.

    The constraint below cannot be added while a rule has two, and
    production has one: AC-MEMBER-AGE-MAX v1 and v2 were both ACTIVE for
    four months, because v2 was approved before `services.approve` learned
    to retire the version it supersedes.

    Highest version wins, which is the same choice both evaluators were
    already making defensively in their ORDER BY — so this changes no
    evaluation outcome. It only makes the state say what the engine was
    already doing.
    """
    DqaRule = apps.get_model("dqa", "DqaRule")
    by_rule = {}
    for rule in DqaRule.objects.filter(status="active").order_by("rule_id", "-version"):
        by_rule.setdefault(rule.rule_id, []).append(rule)

    retired = 0
    for rule_id, versions in by_rule.items():
        for superseded in versions[1:]:        # [0] is the highest
            superseded.status = "retired"
            superseded.save(update_fields=["status"])
            retired += 1
            print(
                f"\n  {rule_id} v{superseded.version} retired "
                f"(superseded by v{versions[0].version})"
            )
    if not retired:
        print("\n  no rule had more than one active version")


def unretire(apps, schema_editor):
    """Deliberately not reversible in data terms.

    Re-activating a superseded version would put the registry back into
    the state this migration exists to end, and there is no record of
    which retirements were this migration's doing. Dropping the
    constraint is the reversal; the statuses stay.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0004_us_s11_044_intra_household_schema'),
    ]

    operations = [
        # Data first: the constraint cannot be added while a rule has two
        # active versions.
        migrations.RunPython(retire_superseded_actives, unretire),
        migrations.AddConstraint(
            model_name='dqarule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('rule_id',), name='dqarule_one_active_version_per_rule'),
        ),
    ]
