# Generated by Django 5.2.14 on 2026-05-19 15:21

import django.db.models.deletion
import nsr_mis.common.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code shown as the partner mark (OPM, UBOS, ...). 3-5 uppercase letters by convention.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "registration_no",
                    models.CharField(
                        blank=True,
                        help_text="URSB / NGO Bureau / Ministerial / IGO charter reference.",
                        max_length=128,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=128)),
                ("website", models.URLField(blank=True)),
                ("primary_email", models.EmailField(blank=True, max_length=254)),
                ("type", models.CharField(max_length=32)),
                ("sector", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(default="onboarding", max_length=32)),
                ("tone", models.CharField(blank=True, max_length=32)),
                (
                    "logo_short",
                    models.CharField(
                        blank=True,
                        help_text="Optional override for the visible mark when `code` isn't the right glyph (e.g. multi-word ministries).",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partners_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "indexes": [
                    models.Index(
                        fields=["status"], name="partners_pa_status_f04d03_idx"
                    ),
                    models.Index(fields=["type"], name="partners_pa_type_999000_idx"),
                    models.Index(
                        fields=["last_activity_at"],
                        name="partners_pa_last_ac_d72f3d_idx",
                    ),
                ],
            },
        ),
    ]
