# Generated by Django 5.2.14 on 2026-05-19 15:25

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("reference_data", "0004_seed_partner_choice_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerContact",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=32)),
                ("full_name", models.CharField(max_length=128)),
                ("title", models.CharField(blank=True, max_length=128)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_e164",
                    models.CharField(
                        blank=True,
                        help_text="E.164 format including leading + (e.g. +256772000000).",
                        max_length=20,
                    ),
                ),
                (
                    "nin_value",
                    nsr_mis.common.fields.EncryptedBinaryField(blank=True, null=True),
                ),
                ("nin_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                ("nin_last4", models.CharField(blank=True, max_length=4)),
                ("nin_verified_at", models.DateTimeField(blank=True, null=True)),
                ("supporting_doc_ref", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner contact",
                "verbose_name_plural": "Partner contacts",
                "indexes": [
                    models.Index(
                        fields=["partner", "role"],
                        name="partners_pa_partner_9f1fc1_idx",
                    ),
                    models.Index(
                        fields=["nin_hash"], name="partners_pa_nin_has_0dc5b5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "role"),
                        name="partner_contact_unique_role_per_partner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("kind", models.CharField(max_length=32)),
                ("status", models.CharField(default="draft", max_length=32)),
                (
                    "scope_text",
                    models.TextField(
                        blank=True,
                        help_text="Free-text geographic / cohort scope. Structured GeographicUnit M2M lives on the DSA per ADR-0011.",
                    ),
                ),
                (
                    "beneficiary_estimate",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geographic_units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="programmes",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programmes",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "indexes": [
                    models.Index(
                        fields=["partner"], name="partners_pr_partner_170536_idx"
                    ),
                    models.Index(
                        fields=["status"], name="partners_pr_status_b453af_idx"
                    ),
                ],
            },
        ),
    ]
