# Generated by Django 5.2.14 on 2026-05-19 15:28

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_partnercontact_programme"),
        ("reference_data", "0004_seed_partner_choice_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSharingAgreement",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Human-readable identifier (DSA-OPM-2026-001).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="draft", max_length=32)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "monthly_row_budget",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "entities_scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"household": true, "member": false, "referral": true, "grievance": false}',
                    ),
                ),
                (
                    "field_scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"Identifiers": true, "PMT": true, ...}',
                    ),
                ),
                (
                    "sensitive_data_handling",
                    models.CharField(default="none", max_length=32),
                ),
                ("retention_days", models.PositiveIntegerField(default=180)),
                ("classification", models.CharField(blank=True, max_length=128)),
                (
                    "dpia_document_ref",
                    models.CharField(
                        blank=True,
                        help_text="DPIA PDF reference (storage abstraction lands with DRS-O-02).",
                        max_length=128,
                    ),
                ),
                (
                    "breach_sla_hours",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="Hours from breach detection to partner-side notification of the NSR DPO.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geographic_scope",
                    models.ManyToManyField(
                        blank=True,
                        help_text="DSA scope at any geographic level (ADR-0011 decision 4).",
                        related_name="dsas",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dsas",
                        to="partners.partner",
                    ),
                ),
                (
                    "programmes",
                    models.ManyToManyField(
                        blank=True, related_name="dsas", to="partners.programme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Sharing Agreement",
                "verbose_name_plural": "Data Sharing Agreements",
            },
        ),
        migrations.CreateModel(
            name="DsaSignature",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sequence_order",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3 — order in which the signature is collected."
                    ),
                ),
                ("signer_role", models.CharField(max_length=32)),
                ("signer_name", models.CharField(blank=True, max_length=128)),
                ("signer_email", models.EmailField(max_length=254)),
                ("method", models.CharField(default="docusign", max_length=32)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("docusign_envelope_id", models.CharField(blank=True, max_length=64)),
                ("evidence_doc_ref", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="partners.datasharingagreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "DSA signature",
                "verbose_name_plural": "DSA signatures",
                "ordering": ("dsa", "sequence_order"),
            },
        ),
        migrations.AddIndex(
            model_name="datasharingagreement",
            index=models.Index(
                fields=["partner", "status"], name="partners_da_partner_eb3b03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasharingagreement",
            index=models.Index(
                fields=["effective_to"], name="partners_da_effecti_41b817_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="datasharingagreement",
            constraint=models.UniqueConstraint(
                fields=("reference", "version"), name="dsa_reference_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="datasharingagreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="dsa_effective_to_after_from",
            ),
        ),
        migrations.AddIndex(
            model_name="dsasignature",
            index=models.Index(
                fields=["dsa", "status"], name="partners_ds_dsa_id_d73445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dsasignature",
            index=models.Index(
                fields=["docusign_envelope_id"], name="partners_ds_docusig_7bb4de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dsasignature",
            constraint=models.UniqueConstraint(
                fields=("dsa", "sequence_order"),
                name="dsa_signature_unique_order_per_dsa",
            ),
        ),
        migrations.AddConstraint(
            model_name="dsasignature",
            constraint=models.UniqueConstraint(
                fields=("dsa", "signer_email"),
                name="dsa_signature_unique_email_per_dsa",
            ),
        ),
    ]
