# Generated by Django 5.2.14 on 2026-05-19 15:32

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_datasharingagreement_dsasignature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerUsageDaily",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("day", models.DateField()),
                ("rows_delivered", models.PositiveIntegerField(default=0)),
                ("requests_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_daily",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner usage (daily)",
                "verbose_name_plural": "Partner usage (daily)",
                "ordering": ("-day", "partner"),
                "indexes": [
                    models.Index(
                        fields=["partner", "day"], name="partners_pa_partner_6c4620_idx"
                    ),
                    models.Index(fields=["day"], name="partners_pa_day_69baba_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "day"),
                        name="partner_usage_daily_unique_per_day",
                    )
                ],
            },
        ),
    ]
