# Generated by Django 5.2.14 on 2026-05-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partnerusagedaily"),
        ("reference_data", "0005_seed_programme_choice_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="age_max",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="age_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="amount_ugx",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="auto_exit_triggers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of programme_auto_exit_trigger codes.",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="channel",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="programme",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Short programme mark (MGLSD-DVA). Unique per partner.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="cohort_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="composition_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of programme_composition_flag codes, e.g. ["female_headed", "under_five"].',
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="disbursement_cycle",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="programme",
            name="dsa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes_via_fk",
                to="partners.datasharingagreement",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="duration_months",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="exit_codes_allowed",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of programme_exit_reason codes, e.g. ["10","20","30","40","50","60","70"].',
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="pmt_bands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of programme_pmt_band codes, e.g. ["poorest_20", "poorest_40"].',
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="sex_filter",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="programme",
            name="start_month",
            field=models.CharField(
                blank=True,
                help_text="Free-text 'Aug 2026' — first cycle target. Concrete calendar lands when the scheduler app boots.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="One-sentence description shown in the partner programmes tab and the registration wizard preview.",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="suspend_on_grievance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programme",
            name="unit_of_enrolment",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="programme",
            name="webhook_secret_hash",
            field=models.CharField(
                blank=True,
                help_text="sha256(webhook_secret). The cleartext secret is returned in the create response and never persisted.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="webhook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(fields=["dsa"], name="partners_pr_dsa_id_3ec418_idx"),
        ),
        migrations.AddConstraint(
            model_name="programme",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__gt", "")),
                fields=("partner", "code"),
                name="programme_partner_code_unique",
            ),
        ),
    ]
