# Generated by Django 5.2.14 on 2026-05-20 09:53

import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_programme_wizard_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="dsa_reference_legacy",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="programme",
            name="webhook_secret_encrypted",
            field=nsr_mis.common.fields.EncryptedBinaryField(blank=True, null=True),
        ),
    ]
