# Generated by Django 5.2.14 on 2026-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_programme_webhook_secret_encrypted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasharingagreement",
            name="reference",
            field=models.CharField(
                help_text="Human-readable identifier (DSA-OPM-2026-001). Stable across versions: v(N+1) shares the reference of v(N); uniqueness is enforced by the (reference, version) composite constraint.",
                max_length=64,
            ),
        ),
    ]
