# Generated by Django 5.2.14 on 2026-05-22 19:35

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0007_dsa_reference_unique_drop"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="created_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="programme",
            name="current_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ProgrammeSignOff",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("step", models.PositiveSmallIntegerField()),
                ("expected_role", models.CharField(max_length=64)),
                ("expected_email", models.CharField(blank=True, max_length=254)),
                ("actual_email", models.CharField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                            ("on_hold", "On hold"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("audit_event_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signoffs",
                        to="partners.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme sign-off",
                "verbose_name_plural": "Programme sign-offs",
                "ordering": ["programme", "revision", "step"],
                "indexes": [
                    models.Index(
                        fields=["programme", "revision"],
                        name="partners_pr_program_e1157e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="partners_pr_status_4b39f9_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("programme", "revision", "step"),
                        name="programme_signoff_step_unique",
                    )
                ],
            },
        ),
    ]
