# Generated by Django 5.2.14 on 2026-06-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_programme_activated_at_programme_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="pmt_bands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of programme_pmt_band codes, e.g. ["poorest_20", "poorest_40"] (Extreme poverty, Poverty, Vulnerable, Not poor).',
            ),
        ),
    ]
