from django.urls import path

from .dashboard_views import OperatorKpisView
from .views import (
    ComparativeMetric,
    GrievancesByCategory,
    HouseholdsByPmtBand,
    HouseholdsBySubRegion,
    OpenGrievancesByTier,
    OverdueGrievancesByTier,
    PendingDedupPairsByTier,
    PmtScoreHistogram,
    PromotionLatencyByConnector,
    SubmissionsPerDay,
    WeeklyHouseholdRegistrations,
)

urlpatterns = [
    path("dashboards/households-by-sub-region/",
         HouseholdsBySubRegion.as_view(),
         name="rpt-households-by-sub-region"),
    path("dashboards/households-by-pmt-band/",
         HouseholdsByPmtBand.as_view(),
         name="rpt-households-by-pmt-band"),
    path("dashboards/open-grievances-by-tier/",
         OpenGrievancesByTier.as_view(),
         name="rpt-open-grievances-by-tier"),
    path("dashboards/overdue-grievances-by-tier/",
         OverdueGrievancesByTier.as_view(),
         name="rpt-overdue-grievances-by-tier"),
    path("dashboards/submissions-per-day/",
         SubmissionsPerDay.as_view(),
         name="rpt-submissions-per-day"),
    path("dashboards/pending-dedup-pairs-by-tier/",
         PendingDedupPairsByTier.as_view(),
         name="rpt-pending-dedup-pairs-by-tier"),
    path("dashboards/pmt-score-histogram/",
         PmtScoreHistogram.as_view(),
         name="rpt-pmt-score-histogram"),
    path("dashboards/promotion-latency-by-connector/",
         PromotionLatencyByConnector.as_view(),
         name="rpt-promotion-latency-by-connector"),
    path("dashboards/weekly-household-registrations/",
         WeeklyHouseholdRegistrations.as_view(),
         name="rpt-weekly-household-registrations"),
    path("dashboards/grievances-by-category/",
         GrievancesByCategory.as_view(),
         name="rpt-grievances-by-category"),
    path("dashboards/comparative/",
         ComparativeMetric.as_view(),
         name="rpt-comparative"),
    path("dashboards/operator-kpis/",
         OperatorKpisView.as_view(),
         name="rpt-operator-kpis"),
]
