# Generated by Django 5.2.14 on 2026-05-15 02:36

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("schema", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form version",
                "indexes": [
                    models.Index(
                        fields=["is_active", "effective_from"],
                        name="intake_form_is_acti_404d2c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("capi", "Capi"),
                            ("web", "Web"),
                            ("ussd", "Ussd"),
                            ("bulk", "Bulk"),
                            ("partner_mis", "Partner Mis"),
                        ],
                        max_length=16,
                    ),
                ),
                ("enumerator", models.CharField(max_length=64)),
                ("supervisor", models.CharField(blank=True, max_length=64)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("refused", "Refused"),
                            ("not_at_home", "Not At Home"),
                            ("partial", "Partial"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_qa", "Pending Qa"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_qa",
                        max_length=24,
                    ),
                ),
                (
                    "stage_record_id",
                    models.CharField(blank=True, db_index=True, max_length=26),
                ),
                (
                    "provisional_registry_id",
                    models.CharField(blank=True, db_index=True, max_length=26),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="intake.formversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "indexes": [
                    models.Index(
                        fields=["channel", "-created_at"],
                        name="intake_subm_channel_57b49b_idx",
                    ),
                    models.Index(fields=["state"], name="intake_subm_state_5328ce_idx"),
                    models.Index(
                        fields=["enumerator"], name="intake_subm_enumera_334ecd_idx"
                    ),
                ],
            },
        ),
    ]
