# Generated by Django 5.2.14 on 2026-05-16 16:27

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
        ("reference_data", "0003_seed_choice_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormConstraint",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("dsl", models.JSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, max_length=256)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form constraint",
            },
        ),
        migrations.CreateModel(
            name="FormQuestion",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=512)),
                ("hint", models.CharField(blank=True, max_length=512)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("date", "Date"),
                            ("select_one", "Select One"),
                            ("select_multiple", "Select Multiple"),
                            ("geopoint", "Geopoint"),
                            ("image", "Image"),
                            ("calculate", "Calculate"),
                            ("note", "Note"),
                            ("begin_repeat", "Begin Repeat"),
                            ("end_repeat", "End Repeat"),
                            ("begin_group", "Begin Group"),
                            ("end_group", "End Group"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("relevant_expression", models.CharField(blank=True, max_length=512)),
                ("constraint_expression", models.CharField(blank=True, max_length=512)),
                ("constraint_message", models.CharField(blank=True, max_length=256)),
                ("appearance", models.CharField(blank=True, max_length=64)),
                ("repeat_count", models.CharField(blank=True, max_length=64)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("order_in_section", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form question",
                "ordering": ("section", "order_in_section", "name"),
            },
        ),
        migrations.CreateModel(
            name="FormSection",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form section",
                "ordering": ("form_version", "order", "code"),
            },
        ),
        migrations.CreateModel(
            name="FormSkipLogic",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("dsl", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form skip-logic",
                "verbose_name_plural": "Form skip-logic",
            },
        ),
        migrations.AddField(
            model_name="formversion",
            name="approval_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="formversion",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formversion",
            name="approved_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="formversion",
            name="author",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="formversion",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="formversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="formversion",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="formversion",
            index=models.Index(
                fields=["status", "version"], name="intake_form_status_355f5e_idx"
            ),
        ),
        migrations.AddField(
            model_name="formquestion",
            name="choice_list_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referenced_by_questions",
                to="reference_data.choicelist",
            ),
        ),
        migrations.AddField(
            model_name="formconstraint",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints",
                to="intake.formquestion",
            ),
        ),
        migrations.AddField(
            model_name="formsection",
            name="form_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="intake.formversion",
            ),
        ),
        migrations.AddField(
            model_name="formquestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="intake.formsection",
            ),
        ),
        migrations.AddField(
            model_name="formskiplogic",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skip_logic",
                to="intake.formquestion",
            ),
        ),
        migrations.AddConstraint(
            model_name="formsection",
            constraint=models.UniqueConstraint(
                fields=("form_version", "code"), name="formsection_unique_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="formsection",
            constraint=models.UniqueConstraint(
                fields=("form_version", "name"),
                name="formsection_name_unique_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="formquestion",
            constraint=models.UniqueConstraint(
                fields=("section", "name"), name="formquestion_name_unique_per_section"
            ),
        ),
    ]
