# Generated by Django 5.2.14 on 2026-05-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_questionnaire_authoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsection",
            name="repeat_count",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="formquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("dateTime", "Datetime"),
                    ("select_one", "Select One"),
                    ("select_multiple", "Select Multiple"),
                    ("geopoint", "Geopoint"),
                    ("geotrace", "Geotrace"),
                    ("geoshape", "Geoshape"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("file", "File"),
                    ("barcode", "Barcode"),
                    ("calculate", "Calculate"),
                    ("note", "Note"),
                    ("acknowledge", "Acknowledge"),
                    ("hidden", "Hidden"),
                    ("range", "Range"),
                    ("rank", "Rank"),
                    ("start", "Start"),
                    ("end", "End"),
                    ("today", "Today"),
                    ("deviceid", "Deviceid"),
                    ("username", "Username"),
                    ("phonenumber", "Phonenumber"),
                    ("begin_repeat", "Begin Repeat"),
                    ("end_repeat", "End Repeat"),
                    ("begin_group", "Begin Group"),
                    ("end_group", "End Group"),
                ],
                max_length=24,
            ),
        ),
    ]
