# Generated by Django 5.2.14 on 2026-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_formsection_repeat_count_alter_formquestion_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="kobo_asset_uid",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
