# Generated by Django 5.2.14 on 2026-05-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0004_formversion_kobo_asset_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="formquestion",
            name="calculation",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
