# Generated by Django 5.2.17 on 2026-09-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_alter_submission_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='canonical_field',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
