# Generated by Django 5.2.17 on 2026-09-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_seed_canonical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='payload_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
