# Generated by Django 5.2.14 on 2026-05-14 16:33

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "urban_rural",
                    models.CharField(
                        choices=[
                            ("urban", "Urban"),
                            ("rural", "Rural"),
                            ("peri_urban", "Peri Urban"),
                        ],
                        max_length=16,
                    ),
                ),
                ("enumeration_area", models.CharField(blank=True, max_length=32)),
                ("household_number", models.CharField(blank=True, max_length=32)),
                ("address_narrative", models.TextField(blank=True)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("dwelling_tenure", models.CharField(blank=True, max_length=32)),
                ("residence_status", models.CharField(blank=True, max_length=32)),
                (
                    "current_pmt_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "current_vulnerability_band",
                    models.CharField(blank=True, max_length=16),
                ),
                ("current_consent_state", models.CharField(blank=True, max_length=16)),
                ("current_intake_source", models.CharField(blank=True, max_length=16)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_county",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_district",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_parish",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_region",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_sub_county",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "sub_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_sub_region",
                        to="reference_data.geographicunit",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="households_in_village",
                        to="reference_data.geographicunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household",
                "verbose_name_plural": "Households",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("line_number", models.PositiveSmallIntegerField()),
                ("surname", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=64)),
                ("other_name", models.CharField(blank=True, max_length=64)),
                ("relationship_to_head", models.CharField(max_length=32)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("marital_status", models.CharField(blank=True, max_length=32)),
                ("nationality", models.CharField(blank=True, max_length=32)),
                ("residency_status", models.CharField(blank=True, max_length=32)),
                (
                    "birth_certificate_status",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "nin_status",
                    models.CharField(
                        choices=[
                            ("has_card", "Has Card"),
                            ("lost", "Lost"),
                            ("not_issued", "Not Issued"),
                            ("no", "No"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "nin_value",
                    nsr_mis.common.fields.EncryptedBinaryField(blank=True, null=True),
                ),
                ("nin_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                ("nin_last4", models.CharField(blank=True, max_length=4)),
                ("telephone_1", models.CharField(blank=True, max_length=20)),
                ("telephone_2", models.CharField(blank=True, max_length=20)),
                ("telephone_in_name_flag", models.BooleanField(default=False)),
                ("mobile_money_flag", models.BooleanField(default=False)),
                ("mother_alive_flag", models.BooleanField(blank=True, null=True)),
                ("father_alive_flag", models.BooleanField(blank=True, null=True)),
                (
                    "mother_line_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "father_line_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "identification_documents",
                    models.JSONField(blank=True, default=list),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="data_management.household",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_aliases",
                        to="data_management.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
        migrations.AddField(
            model_name="household",
            name="head_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="head_of_household",
                to="data_management.member",
            ),
        ),
        migrations.CreateModel(
            name="MemberVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("surname", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(blank=True, max_length=64)),
                ("other_name", models.CharField(blank=True, max_length=64)),
                ("relationship_to_head", models.CharField(blank=True, max_length=32)),
                ("marital_status", models.CharField(blank=True, max_length=32)),
                ("nationality", models.CharField(blank=True, max_length=32)),
                ("residency_status", models.CharField(blank=True, max_length=32)),
                (
                    "birth_certificate_status",
                    models.CharField(blank=True, max_length=32),
                ),
                ("nin_status", models.CharField(blank=True, max_length=16)),
                ("nin_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                ("nin_last4", models.CharField(blank=True, max_length=4)),
                ("telephone_1", models.CharField(blank=True, max_length=20)),
                ("telephone_2", models.CharField(blank=True, max_length=20)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member version",
                "verbose_name_plural": "Member versions",
            },
        ),
        migrations.CreateModel(
            name="HouseholdVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("head_member_id", models.CharField(blank=True, max_length=26)),
                ("urban_rural", models.CharField(blank=True, max_length=16)),
                ("address_narrative", models.TextField(blank=True)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("dwelling_tenure", models.CharField(blank=True, max_length=32)),
                ("residence_status", models.CharField(blank=True, max_length=32)),
                (
                    "current_pmt_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "current_vulnerability_band",
                    models.CharField(blank=True, max_length=16),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "Household version",
                "verbose_name_plural": "Household versions",
                "indexes": [
                    models.Index(
                        fields=["household", "effective_from"],
                        name="data_manage_househo_40425a_idx",
                    ),
                    models.Index(
                        fields=["household", "effective_to"],
                        name="data_manage_househo_685f69_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "version_number"),
                        name="household_version_number_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["household"], name="data_manage_househo_4dc37a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["nin_hash"], name="data_manage_nin_has_83bdec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["telephone_1"], name="data_manage_telepho_3084f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["surname", "first_name"], name="data_manage_surname_056069_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("household", "line_number"),
                name="member_line_unique_per_household",
            ),
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(
                fields=["village"], name="data_manage_village_7ab2f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(
                fields=["parish"], name="data_manage_parish__292848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(
                fields=["is_deleted", "updated_at"],
                name="data_manage_is_dele_bcb17a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memberversion",
            index=models.Index(
                fields=["member", "effective_from"],
                name="data_manage_member__d35eca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memberversion",
            index=models.Index(
                fields=["member", "effective_to"], name="data_manage_member__b737fc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberversion",
            constraint=models.UniqueConstraint(
                fields=("member", "version_number"), name="member_version_number_unique"
            ),
        ),
    ]
