# Generated by Django 5.2.14 on 2026-05-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="sub_region_code",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="member",
            name="sub_region_code",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(
                fields=["sub_region_code", "id"], name="data_manage_sub_reg_a274d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["sub_region_code", "id"], name="data_manage_sub_reg_fe0f32_idx"
            ),
        ),
    ]
