# Generated by Django 5.2.14 on 2026-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_backfill_sub_region_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household",
            name="urban_rural",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="member",
            name="nin_status",
            field=models.CharField(blank=True, default="8", max_length=32),
        ),
        migrations.AlterField(
            model_name="member",
            name="sex",
            field=models.CharField(max_length=32),
        ),
    ]
