# Generated by Django 5.2.14 on 2026-05-21 10:33

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0005_coded_fields_to_choiceoption_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOwnership",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_type", models.CharField(max_length=32)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="data_management.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetOwnershipVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("asset_type", models.CharField(blank=True, max_length=32)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.assetownership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset version",
            },
        ),
        migrations.CreateModel(
            name="CopingStrategy",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("strategy_type", models.CharField(max_length=32)),
                ("category", models.CharField(max_length=16)),
                ("frequency", models.CharField(blank=True, max_length=32)),
                ("used_flag", models.BooleanField(default=False)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coping_strategies",
                        to="data_management.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopingStrategyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("strategy_type", models.CharField(blank=True, max_length=32)),
                ("category", models.CharField(blank=True, max_length=16)),
                ("frequency", models.CharField(blank=True, max_length=32)),
                ("used_flag", models.BooleanField(default=False)),
                (
                    "coping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.copingstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coping strategy version",
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crop_name", models.CharField(max_length=32)),
                ("rank_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crops",
                        to="data_management.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("crop_name", models.CharField(blank=True, max_length=32)),
                ("rank_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.crop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop version",
            },
        ),
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seeing", models.CharField(blank=True, max_length=4)),
                ("hearing", models.CharField(blank=True, max_length=4)),
                ("walking", models.CharField(blank=True, max_length=4)),
                ("memory", models.CharField(blank=True, max_length=4)),
                ("selfcare", models.CharField(blank=True, max_length=4)),
                ("communication", models.CharField(blank=True, max_length=4)),
                ("wg_disability_flag", models.BooleanField(default=False)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disability",
                        to="data_management.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DisabilityVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("seeing", models.CharField(blank=True, max_length=4)),
                ("hearing", models.CharField(blank=True, max_length=4)),
                ("walking", models.CharField(blank=True, max_length=4)),
                ("memory", models.CharField(blank=True, max_length=4)),
                ("selfcare", models.CharField(blank=True, max_length=4)),
                ("communication", models.CharField(blank=True, max_length=4)),
                ("wg_disability_flag", models.BooleanField(default=False)),
                (
                    "disability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.disability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disability version",
            },
        ),
        migrations.CreateModel(
            name="Dwelling",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenure", models.CharField(blank=True, max_length=32)),
                ("dwelling_type", models.CharField(blank=True, max_length=32)),
                (
                    "total_rooms",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sleeping_rooms",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("roof_material", models.CharField(blank=True, max_length=32)),
                ("wall_material", models.CharField(blank=True, max_length=32)),
                ("floor_material", models.CharField(blank=True, max_length=32)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dwelling",
                        to="data_management.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DwellingVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("tenure", models.CharField(blank=True, max_length=32)),
                ("dwelling_type", models.CharField(blank=True, max_length=32)),
                (
                    "total_rooms",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sleeping_rooms",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("roof_material", models.CharField(blank=True, max_length=32)),
                ("wall_material", models.CharField(blank=True, max_length=32)),
                ("floor_material", models.CharField(blank=True, max_length=32)),
                (
                    "dwelling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.dwelling",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dwelling version",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("literacy_status", models.CharField(blank=True, max_length=8)),
                ("ever_attended", models.CharField(blank=True, max_length=8)),
                ("never_attended_reason", models.CharField(blank=True, max_length=8)),
                ("highest_grade", models.CharField(blank=True, max_length=8)),
                ("currently_attending", models.CharField(blank=True, max_length=8)),
                ("why_stopped", models.CharField(blank=True, max_length=8)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="education",
                        to="data_management.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EducationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("literacy_status", models.CharField(blank=True, max_length=8)),
                ("ever_attended", models.CharField(blank=True, max_length=8)),
                ("never_attended_reason", models.CharField(blank=True, max_length=8)),
                ("highest_grade", models.CharField(blank=True, max_length=8)),
                ("currently_attending", models.CharField(blank=True, max_length=8)),
                ("why_stopped", models.CharField(blank=True, max_length=8)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.education",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education version",
            },
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_activity_last_30d", models.CharField(blank=True, max_length=8)),
                ("work_frequency", models.CharField(blank=True, max_length=8)),
                ("sector", models.CharField(blank=True, max_length=8)),
                ("employment_status", models.CharField(blank=True, max_length=8)),
                ("not_working_reason", models.CharField(blank=True, max_length=8)),
                (
                    "is_govt_programme_beneficiary",
                    models.CharField(blank=True, max_length=8),
                ),
                ("programmes_benefited", models.JSONField(blank=True, default=list)),
                ("currently_benefiting", models.CharField(blank=True, max_length=8)),
                ("made_savings", models.CharField(blank=True, max_length=8)),
                ("savings_location", models.CharField(blank=True, max_length=8)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employment",
                        to="data_management.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("main_activity_last_30d", models.CharField(blank=True, max_length=8)),
                ("work_frequency", models.CharField(blank=True, max_length=8)),
                ("sector", models.CharField(blank=True, max_length=8)),
                ("employment_status", models.CharField(blank=True, max_length=8)),
                ("not_working_reason", models.CharField(blank=True, max_length=8)),
                (
                    "is_govt_programme_beneficiary",
                    models.CharField(blank=True, max_length=8),
                ),
                ("programmes_benefited", models.JSONField(blank=True, default=list)),
                ("currently_benefiting", models.CharField(blank=True, max_length=8)),
                ("made_savings", models.CharField(blank=True, max_length=8)),
                ("savings_location", models.CharField(blank=True, max_length=8)),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.employment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment version",
            },
        ),
        migrations.CreateModel(
            name="FoodConsumption",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("staples_days", models.PositiveSmallIntegerField(default=0)),
                ("pulses_days", models.PositiveSmallIntegerField(default=0)),
                ("dairy_days", models.PositiveSmallIntegerField(default=0)),
                ("meat_days", models.PositiveSmallIntegerField(default=0)),
                ("vegetables_days", models.PositiveSmallIntegerField(default=0)),
                ("fruits_days", models.PositiveSmallIntegerField(default=0)),
                ("oils_days", models.PositiveSmallIntegerField(default=0)),
                ("sugar_days", models.PositiveSmallIntegerField(default=0)),
                ("condiments_days", models.PositiveSmallIntegerField(default=0)),
                ("staples_source", models.CharField(blank=True, max_length=32)),
                ("pulses_source", models.CharField(blank=True, max_length=32)),
                ("dairy_source", models.CharField(blank=True, max_length=32)),
                ("meat_source", models.CharField(blank=True, max_length=32)),
                ("vegetables_source", models.CharField(blank=True, max_length=32)),
                ("fruits_source", models.CharField(blank=True, max_length=32)),
                ("oils_source", models.CharField(blank=True, max_length=32)),
                ("sugar_source", models.CharField(blank=True, max_length=32)),
                ("condiments_source", models.CharField(blank=True, max_length=32)),
                (
                    "fcs_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_consumption",
                        to="data_management.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoodConsumptionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("staples_days", models.PositiveSmallIntegerField(default=0)),
                ("pulses_days", models.PositiveSmallIntegerField(default=0)),
                ("dairy_days", models.PositiveSmallIntegerField(default=0)),
                ("meat_days", models.PositiveSmallIntegerField(default=0)),
                ("vegetables_days", models.PositiveSmallIntegerField(default=0)),
                ("fruits_days", models.PositiveSmallIntegerField(default=0)),
                ("oils_days", models.PositiveSmallIntegerField(default=0)),
                ("sugar_days", models.PositiveSmallIntegerField(default=0)),
                ("condiments_days", models.PositiveSmallIntegerField(default=0)),
                ("staples_source", models.CharField(blank=True, max_length=32)),
                ("pulses_source", models.CharField(blank=True, max_length=32)),
                ("dairy_source", models.CharField(blank=True, max_length=32)),
                ("meat_source", models.CharField(blank=True, max_length=32)),
                ("vegetables_source", models.CharField(blank=True, max_length=32)),
                ("fruits_source", models.CharField(blank=True, max_length=32)),
                ("oils_source", models.CharField(blank=True, max_length=32)),
                ("sugar_source", models.CharField(blank=True, max_length=32)),
                ("condiments_source", models.CharField(blank=True, max_length=32)),
                (
                    "fcs_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "food_consumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.foodconsumption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food consumption version",
            },
        ),
        migrations.CreateModel(
            name="FoodSecurity",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worried_food", models.CharField(blank=True, max_length=4)),
                ("unhealthy_food", models.CharField(blank=True, max_length=4)),
                ("limited_variety", models.CharField(blank=True, max_length=4)),
                ("skipped_meal", models.CharField(blank=True, max_length=4)),
                ("ate_less", models.CharField(blank=True, max_length=4)),
                ("ran_out_food", models.CharField(blank=True, max_length=4)),
                ("hungry_no_eat", models.CharField(blank=True, max_length=4)),
                ("whole_day_no_eat", models.CharField(blank=True, max_length=4)),
                ("fies_raw_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_security",
                        to="data_management.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoodSecurityVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("worried_food", models.CharField(blank=True, max_length=4)),
                ("unhealthy_food", models.CharField(blank=True, max_length=4)),
                ("limited_variety", models.CharField(blank=True, max_length=4)),
                ("skipped_meal", models.CharField(blank=True, max_length=4)),
                ("ate_less", models.CharField(blank=True, max_length=4)),
                ("ran_out_food", models.CharField(blank=True, max_length=4)),
                ("hungry_no_eat", models.CharField(blank=True, max_length=4)),
                ("whole_day_no_eat", models.CharField(blank=True, max_length=4)),
                ("fies_raw_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "food_security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.foodsecurity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food security version",
            },
        ),
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chronic_illness_flag", models.CharField(blank=True, max_length=8)),
                (
                    "chronic_illness_types_encrypted",
                    nsr_mis.common.fields.EncryptedBinaryField(blank=True, null=True),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health",
                        to="data_management.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("chronic_illness_flag", models.CharField(blank=True, max_length=8)),
                (
                    "chronic_illness_types_encrypted",
                    nsr_mis.common.fields.EncryptedBinaryField(blank=True, null=True),
                ),
                (
                    "health",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.health",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health version",
            },
        ),
        migrations.CreateModel(
            name="Livelihood",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_livelihood", models.CharField(blank=True, max_length=32)),
                ("crop_production_zone", models.CharField(blank=True, max_length=32)),
                ("livestock_zone", models.CharField(blank=True, max_length=32)),
                ("agricultural_purpose", models.CharField(blank=True, max_length=32)),
                ("land_ownership", models.CharField(blank=True, max_length=32)),
                (
                    "land_hectares",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("land_title", models.CharField(blank=True, max_length=32)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livelihood",
                        to="data_management.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LivelihoodVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("main_livelihood", models.CharField(blank=True, max_length=32)),
                ("crop_production_zone", models.CharField(blank=True, max_length=32)),
                ("livestock_zone", models.CharField(blank=True, max_length=32)),
                ("agricultural_purpose", models.CharField(blank=True, max_length=32)),
                ("land_ownership", models.CharField(blank=True, max_length=32)),
                (
                    "land_hectares",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("land_title", models.CharField(blank=True, max_length=32)),
                (
                    "livelihood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.livelihood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livelihood version",
            },
        ),
        migrations.CreateModel(
            name="Livestock",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("livestock_type", models.CharField(max_length=32)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livestock",
                        to="data_management.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LivestockVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("livestock_type", models.CharField(blank=True, max_length=32)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "livestock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.livestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livestock version",
            },
        ),
        migrations.CreateModel(
            name="Shock",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shock_type", models.CharField(max_length=32)),
                ("livelihoods_affected", models.JSONField(blank=True, default=list)),
                ("severity", models.CharField(blank=True, max_length=32)),
                (
                    "crops_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "livestock_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "labour_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "other_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shocks",
                        to="data_management.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShockVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("shock_type", models.CharField(blank=True, max_length=32)),
                ("livelihoods_affected", models.JSONField(blank=True, default=list)),
                ("severity", models.CharField(blank=True, max_length=32)),
                (
                    "crops_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "livestock_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "labour_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "other_severity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "shock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.shock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shock version",
            },
        ),
        migrations.CreateModel(
            name="Utilities",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cooking_fuel", models.CharField(blank=True, max_length=32)),
                ("lighting_energy", models.CharField(blank=True, max_length=32)),
                ("drinking_water_source", models.CharField(blank=True, max_length=32)),
                ("toilet_facility", models.CharField(blank=True, max_length=32)),
                ("toilet_shared", models.BooleanField(blank=True, null=True)),
                (
                    "households_sharing_toilet",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("waste_disposal", models.CharField(blank=True, max_length=32)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilities",
                        to="data_management.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UtilitiesVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_request_id", models.CharField(blank=True, max_length=26)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("cooking_fuel", models.CharField(blank=True, max_length=32)),
                ("lighting_energy", models.CharField(blank=True, max_length=32)),
                ("drinking_water_source", models.CharField(blank=True, max_length=32)),
                ("toilet_facility", models.CharField(blank=True, max_length=32)),
                ("toilet_shared", models.BooleanField(blank=True, null=True)),
                (
                    "households_sharing_toilet",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("waste_disposal", models.CharField(blank=True, max_length=32)),
                (
                    "utilities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="data_management.utilities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilities version",
            },
        ),
        migrations.AddIndex(
            model_name="assetownership",
            index=models.Index(
                fields=["sub_region_code", "asset_type"],
                name="data_manage_sub_reg_8d54c6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetownership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("household", "asset_type"),
                name="asset_owner_unique_per_household",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetownershipversion",
            constraint=models.UniqueConstraint(
                fields=("asset", "version_number"), name="asset_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="copingstrategy",
            index=models.Index(
                fields=["sub_region_code", "category"],
                name="data_manage_sub_reg_ec236a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="copingstrategy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("household", "strategy_type", "category"),
                name="coping_unique_per_household_strategy",
            ),
        ),
        migrations.AddConstraint(
            model_name="copingstrategyversion",
            constraint=models.UniqueConstraint(
                fields=("coping", "version_number"), name="coping_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["sub_region_code", "crop_name"],
                name="data_manage_sub_reg_dfa343_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="crop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("household", "crop_name"),
                name="crop_unique_per_household",
            ),
        ),
        migrations.AddConstraint(
            model_name="cropversion",
            constraint=models.UniqueConstraint(
                fields=("crop", "version_number"), name="crop_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="disabilityversion",
            constraint=models.UniqueConstraint(
                fields=("disability", "version_number"),
                name="disability_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dwellingversion",
            constraint=models.UniqueConstraint(
                fields=("dwelling", "version_number"), name="dwelling_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="educationversion",
            constraint=models.UniqueConstraint(
                fields=("education", "version_number"), name="education_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="employmentversion",
            constraint=models.UniqueConstraint(
                fields=("employment", "version_number"),
                name="employment_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodconsumptionversion",
            constraint=models.UniqueConstraint(
                fields=("food_consumption", "version_number"),
                name="food_consumption_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodsecurityversion",
            constraint=models.UniqueConstraint(
                fields=("food_security", "version_number"),
                name="food_security_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthversion",
            constraint=models.UniqueConstraint(
                fields=("health", "version_number"), name="health_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodversion",
            constraint=models.UniqueConstraint(
                fields=("livelihood", "version_number"),
                name="livelihood_version_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="livestock",
            index=models.Index(
                fields=["sub_region_code", "livestock_type"],
                name="data_manage_sub_reg_f29afb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("household", "livestock_type"),
                name="livestock_unique_per_household",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestockversion",
            constraint=models.UniqueConstraint(
                fields=("livestock", "version_number"), name="livestock_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="shock",
            index=models.Index(
                fields=["household", "event_date"],
                name="data_manage_househo_89b834_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shock",
            index=models.Index(
                fields=["sub_region_code", "shock_type"],
                name="data_manage_sub_reg_5081c1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="shockversion",
            constraint=models.UniqueConstraint(
                fields=("shock", "version_number"), name="shock_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="utilitiesversion",
            constraint=models.UniqueConstraint(
                fields=("utilities", "version_number"), name="utilities_version_unique"
            ),
        ),
    ]
