# Generated by Django 5.2.14 on 2026-05-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0007_backfill_dwelling"),
        ("reference_data", "0014_geounit_cached_counts_and_partial_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="households_in_village",
                to="reference_data.geographicunit",
            ),
        ),
    ]
