"""Denormalise every UBOS geography code onto Household.

`sub_region_code` has mirrored `sub_region.code` since ADR-0005, as the
partition key. Every other level was reached through a join, and that
cost more than a join:

  * ABAC matched `district__code`, `county__code`, `sub_county__code`,
    `parish__code`, `village__code` — one join per level, on the hot
    path of every scoped list query in the registry.
  * The Data Explorer matviews joined `reference_data_geographicunit`
    to project the same codes, which made them *depend* on that table's
    `code` column. Postgres then refuses `ALTER TABLE ... ALTER COLUMN
    TYPE` on it: "cannot alter type of a column used by a view or
    rule". Migration 0013 had to declare an explicit dependency on
    reference_data.0017 to get a from-scratch build to work at all.

Both problems are the same problem — the code lives one join away — and
this closes it. Migration 0015 rebuilds the matviews off these columns
and drops the reference_data coupling entirely.

## Indexes

Each column is indexed because ABAC now filters on it directly; leaving
them unindexed would convert a join into a sequential scan and be
strictly worse than what it replaces. On this database that is seven
instant index builds over a few hundred rows. **At national scale
(12M households) these must be built CONCURRENTLY**, outside a
transaction, before the columns are switched on — `AddField` with
`db_index=True` takes an ACCESS EXCLUSIVE lock for the duration. Doing
it now, while the table is small, is the cheap moment.

## Backfill

Chunked by primary key rather than a single UPDATE, so the statement
stays short and a national-scale run does not hold one transaction open
across 12M rows. The update reads the code straight from
`reference_data_geographicunit`; it does not go through `save()`,
because `save()` would fire the audit machinery for a change that is
not a change — the value is already true, it was simply not written
down.

Reversible: the reverse drops the columns.
"""

# Generated by Django 5.2.17 on 2026-09-23 19:13

from django.db import migrations, models

# level -> (Household FK column, denormalised code column)
_LEVELS = [
    ("region", "region_id", "region_code"),
    ("district", "district_id", "district_code"),
    ("county", "county_id", "county_code"),
    ("sub_county", "sub_county_id", "sub_county_code"),
    ("parish", "parish_id", "parish_code"),
    ("village", "village_id", "village_code"),
]

_CHUNK = 5000


def backfill(apps, schema_editor):
    Household = apps.get_model('data_management', 'Household')
    conn = schema_editor.connection
    ids = list(
        Household.objects.order_by('id').values_list('id', flat=True),
    )
    if not ids:
        return
    for start in range(0, len(ids), _CHUNK):
        batch = ids[start:start + _CHUNK]
        placeholders = ', '.join(['%s'] * len(batch))
        with conn.cursor() as cur:
            for _level, fk, column in _LEVELS:
                cur.execute(
                    f'UPDATE data_management_household h '
                    f'SET {column} = COALESCE(g.code, \'\') '
                    f'FROM reference_data_geographicunit g '
                    f'WHERE g.id = h.{fk} '
                    f'AND h.id IN ({placeholders})',
                    batch,
                )
            # sub_region_code predates this migration and is
            # already populated, but only ever when it was blank —
            # a household moved between sub-regions kept the old
            # code. Re-derive it here so all seven start true.
            cur.execute(
                f'UPDATE data_management_household h '
                f'SET sub_region_code = COALESCE(g.code, \'\') '
                f'FROM reference_data_geographicunit g '
                f'WHERE g.id = h.sub_region_id '
                f'AND h.sub_region_code IS DISTINCT FROM g.code '
                f'AND h.id IN ({placeholders})',
                batch,
            )


def unbackfill(apps, schema_editor):
    # The columns go with the reverse of the AddFields; nothing to
    # undo here. sub_region_code is deliberately left corrected.
    pass



class Migration(migrations.Migration):
    # Not atomic. Adding seven indexed columns and then backfilling them
    # inside one transaction fails on a table that carries triggers:
    #
    #   cannot CREATE INDEX "data_management_household"
    #   because it has pending trigger events
    #
    # Each statement commits on its own instead. The backfill is
    # idempotent — it recomputes each code from the FK — so a partial
    # run is re-runnable rather than a mess to unpick.
    atomic = False


    dependencies = [
        ('data_management', '0013_matview_full_geo_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='county_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='household',
            name='district_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='household',
            name='parish_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='household',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='household',
            name='sub_county_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='household',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
