# Generated by Django 5.2.14 on 2026-05-15 02:40

import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("data_correction", "Data Correction"),
                            ("exclusion_error", "Exclusion Error"),
                            ("inclusion_error", "Inclusion Error"),
                            ("programme_issue", "Programme Issue"),
                            ("operator_conduct", "Operator Conduct"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sub_category", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField()),
                (
                    "household_id",
                    models.CharField(blank=True, db_index=True, max_length=26),
                ),
                ("member_id", models.CharField(blank=True, max_length=26)),
                ("reporter_name", models.CharField(blank=True, max_length=128)),
                ("reporter_phone", models.CharField(blank=True, max_length=20)),
                ("reporter_relationship", models.CharField(blank=True, max_length=32)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("l1_parish_chief", "L1 Parish Chief"),
                            ("l2_cdo", "L2 Cdo"),
                            ("l3_district", "L3 District"),
                            ("l4_nsr_unit", "L4 Nsr Unit"),
                        ],
                        default="l1_parish_chief",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("assigned_to", models.CharField(blank=True, max_length=64)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_narrative", models.TextField(blank=True)),
                (
                    "linked_change_request_id",
                    models.CharField(blank=True, max_length=26),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grievance",
                "indexes": [
                    models.Index(
                        fields=["status", "tier"], name="grievance_g_status_0232dc_idx"
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="grievance_g_categor_c533dd_idx",
                    ),
                    models.Index(
                        fields=["sla_deadline"], name="grievance_g_sla_dea_99195c_idx"
                    ),
                ],
            },
        ),
    ]
