# Generated by Django 5.2.14 on 2026-05-18 15:42

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrievanceTask",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("assigned_to", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=64)),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="grievance.grievance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grievance task",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["grievance", "status"],
                        name="grievance_g_grievan_c45f8c_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="grievance_g_assigne_4f5b25_idx",
                    ),
                ],
            },
        ),
    ]
