# Generated by Django 5.2.14 on 2026-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance", "0003_grm_officer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="closed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="grievance",
            name="closing_narrative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="grievance",
            name="resolved_by",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
