# Generated by Django 5.2.17 on 2026-09-24 12:43

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_grievance_closed_by_grievance_closing_narrative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceComment',
            fields=[
                ('id', nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('task_closed', 'Task Closed')], default='note', max_length=16)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grievance.grievance')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_comments', to='grievance.grievancetask')),
            ],
            options={
                'verbose_name': 'Grievance comment',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['grievance', 'created_at'], name='grievance_g_grievan_b1ddcd_idx')],
            },
        ),
    ]
