"""Copy the household's geography onto every grievance.

A grievance carried `household_id` and nothing else about where it was,
so there was no way to scope the list geographically. The GRM viewset
worked around that with a visibility rule of its own — superuser or the
literal "GRM Officer" group, otherwise only what you are assigned —
while the home dashboard counted the same grievances through the normal
ABAC scope. One concept, two rules, two different numbers on one screen.

These column names match Household's denormalised set exactly, because
apps.security.abac derives its level map from Household.GEO_CODE_FIELDS.
With them present, `scope_q_for_field(user, "sub_region_code")` filters
grievances the same way it filters households.

Backfill: every grievance naming a household takes that household's
codes. A grievance about no household keeps them blank — operator
conduct and programme complaints belong to nobody's district.
"""

# Generated by Django 5.2.17 on 2026-09-24 22:24

from django.db import migrations, models


def _backfill(apps, schema_editor):
    Grievance = apps.get_model("grievance", "Grievance")
    Household = apps.get_model("data_management", "Household")
    columns = (
        "region_code", "sub_region_code", "district_code", "county_code",
        "sub_county_code", "parish_code", "village_code",
    )
    households = {
        h["id"]: h
        for h in Household.objects.values("id", *columns)
    }
    updated = []
    for grievance in Grievance.objects.exclude(household_id="").only(
        "id", "household_id", *columns,
    ):
        household = households.get(grievance.household_id)
        if household is None:
            # A grievance naming a household that is not in the
            # registry. Two exist in production from a demo run; they
            # are left blank rather than guessed at.
            continue
        for column in columns:
            setattr(grievance, column, household[column] or "")
        updated.append(grievance)
    if updated:
        Grievance.objects.bulk_update(updated, list(columns), batch_size=500)


def _unbackfill(apps, schema_editor):
    # The columns go with the reverse of the AddFields.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0014_household_geography_codes"),
        ('grievance', '0005_grievance_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='county_code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grievance',
            name='district_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grievance',
            name='parish_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grievance',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sub_county_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sub_region_code',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grievance',
            name='village_code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.RunPython(_backfill, _unbackfill),
    ]
