# Generated by Django 5.2.17 on 2026-09-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_grievance_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='sla_breach_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='tier_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
