# Generated by Django 5.2.17 on 2026-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_grievance_tier_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrmTierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('l1_parish_chief', 'L1 Parish Chief'), ('l2_cdo', 'L2 Cdo'), ('l3_district', 'L3 District'), ('l4_nsr_unit', 'L4 Nsr Unit')], max_length=24)),
                ('required_role', models.CharField(max_length=32)),
                ('sla_hours', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GRM tier rule',
                'verbose_name_plural': 'GRM tier rules',
                'ordering': ('tier',),
                'indexes': [models.Index(fields=['tier', 'is_active'], name='grievance_g_tier_554391_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tier',), name='grm_tier_unique_active')],
            },
        ),
    ]
