"""Give every grievance a reference people can use.

Three steps, because the column is unique and the table has rows: add
it without the constraint, fill it, then constrain. Adding a unique
blank column to a populated table fails on the second row.

The backfill generates in Python rather than in SQL. Postgres could
produce random base32 far faster, but the alphabet, the grouping and
the collision retry live in apps/grievance/reference.py, and a second
implementation in PL/pgSQL is how two grievances end up with
references generated by different rules. There are eight rows in
production; correctness is worth more than speed here.
"""

from django.db import migrations, models


# Inlined, not imported from apps.grievance.reference.
#
# This migration ran when references were random Crockford base32
# (GRM-7K4P-2QX9). 0011 replaced that scheme with a year sequence and
# renumbered every row, so importing the module here would make a
# historical migration follow the code forward and fail — which it did,
# on the first fresh database built after the change.
#
# A migration reproduces the state as of when it ran. The values these
# produce are overwritten by 0011 minutes later; all that matters is
# that they are distinct, so the unique constraint below can be added.
_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_LENGTH = 8


def _legacy_reference(body):
    return "-".join(["GRM", body[:4], body[4:]])


def backfill(apps, schema_editor):
    import secrets

    ALPHABET, LENGTH = _ALPHABET, _LENGTH
    format_reference = _legacy_reference

    Grievance = apps.get_model("grievance", "Grievance")
    # The historical model has no .reference uniqueness yet, so the
    # seen-set does the work assign() would do against the live table.
    seen = set(
        Grievance.objects.exclude(reference="")
        .values_list("reference", flat=True),
    )
    for grievance in Grievance.objects.filter(reference="").iterator():
        while True:
            candidate = format_reference(
                "".join(secrets.choice(ALPHABET) for _ in range(LENGTH)),
            )
            if candidate not in seen:
                break
        seen.add(candidate)
        grievance.reference = candidate
        grievance.save(update_fields=["reference"])


def unbackfill(apps, schema_editor):
    Grievance = apps.get_model("grievance", "Grievance")
    Grievance.objects.update(reference="")


class Migration(migrations.Migration):
    dependencies = [("grievance", "0009_seed_grm_tier_rules")]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="reference",
            # No db_index here: the unique constraint added below
            # brings its own, and asking for both makes Django build
            # the _like index twice and fail on the second.
            field=models.CharField(blank=True, default="", max_length=16),
            preserve_default=False,
        ),
        migrations.RunPython(backfill, unbackfill),
        migrations.AlterField(
            model_name="grievance",
            name="reference",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
