# Generated by Django 5.2.17 on 2026-09-25 04:10

from django.db import migrations, models


def reissue(apps, schema_editor):
    """Renumber every grievance as GRM-<year>-<n>.

    0010 gave these rows random references — GRM-7K4P-2QX9 — which
    reached production and lasted under an hour before the registry
    owner asked for a year sequence instead. Renumbering is safe
    *because* it is immediate: a reference is a promise that a number
    keeps meaning the same case, and nobody has had time to be given
    one. It would not be safe next week.

    Numbered in the order the cases were opened, so the sequence reads
    the way somebody would expect: the first grievance of 2026 is
    GRM-2026-0001.
    """
    from django.utils import timezone

    Grievance = apps.get_model("grievance", "Grievance")
    GrmReferenceSequence = apps.get_model("grievance", "GrmReferenceSequence")

    counters: dict[int, int] = {}
    for grievance in Grievance.objects.order_by("opened_at", "id").iterator():
        opened = grievance.opened_at or timezone.now()
        year = timezone.localtime(opened).year
        counters[year] = counters.get(year, 0) + 1
        grievance.reference = f"GRM-{year:04d}-{counters[year]:04d}"
        grievance.save(update_fields=["reference"])

    for year, last in counters.items():
        GrmReferenceSequence.objects.update_or_create(
            year=year, defaults={"last_number": last},
        )


def unreissue(apps, schema_editor):
    """There is no going back to the random values — they were not
    recorded anywhere else. Clearing is the honest reverse; 0010's
    backfill will issue fresh ones if it is re-run."""
    Grievance = apps.get_model("grievance", "Grievance")
    Grievance.objects.update(reference="")


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0010_grievance_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrmReferenceSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GRM reference sequence',
                'verbose_name_plural': 'GRM reference sequences',
                'ordering': ('-year',),
            },
        ),
        migrations.RunPython(reissue, unreissue),
    ]
