# Generated by Django 5.2.14 on 2026-05-14 17:02

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DdupModelVersion",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("author", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DDUP model version",
                "indexes": [
                    models.Index(
                        fields=["status"], name="ddup_ddupmo_status_6b964b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchPair",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("record_type", models.CharField(max_length=16)),
                ("record_a_id", models.CharField(max_length=26)),
                ("record_b_id", models.CharField(max_length=26)),
                ("tier", models.PositiveSmallIntegerField()),
                ("match_reason", models.CharField(max_length=64)),
                (
                    "composite_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("per_field_scores", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("merged", "Merged"),
                            ("rejected", "Rejected"),
                            ("on_hold", "On Hold"),
                            ("cross_household", "Cross Household"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pairs",
                        to="ddup.ddupmodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match pair",
            },
        ),
        migrations.CreateModel(
            name="MergeDecision",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("merge", "Merge"),
                            ("reject", "Reject"),
                            ("on_hold", "On Hold"),
                            ("cross_household", "Cross Household"),
                        ],
                        max_length=24,
                    ),
                ),
                ("surviving_record_id", models.CharField(blank=True, max_length=26)),
                ("losing_record_id", models.CharField(blank=True, max_length=26)),
                ("chosen_field_values", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("decided_by", models.CharField(max_length=64)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("reverse_window_until", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_by", models.CharField(blank=True, max_length=64)),
                (
                    "match_pair",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="ddup.matchpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge decision",
            },
        ),
        migrations.AddIndex(
            model_name="matchpair",
            index=models.Index(
                fields=["status", "tier"], name="ddup_matchp_status_fe6640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchpair",
            index=models.Index(
                fields=["record_type", "status"], name="ddup_matchp_record__a259e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchpair",
            constraint=models.UniqueConstraint(
                fields=("record_type", "record_a_id", "record_b_id"),
                name="match_pair_uniqueness",
            ),
        ),
        migrations.AddIndex(
            model_name="mergedecision",
            index=models.Index(
                fields=["decided_at"], name="ddup_merged_decided_9cc588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mergedecision",
            index=models.Index(
                fields=["action", "decided_at"], name="ddup_merged_action_72834a_idx"
            ),
        ),
    ]
