# Generated by Django 5.2.14 on 2026-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedecision",
            name="pre_merge_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="mergedecision",
            name="reversed_reason",
            field=models.TextField(blank=True),
        ),
    ]
