# Generated by Django 5.2.14 on 2026-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddup", "0002_mergedecision_pre_merge_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergedecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("merge", "Merge"),
                    ("reject", "Reject"),
                    ("on_hold", "On Hold"),
                    ("cross_household", "Cross Household"),
                    ("discard_loser", "Discard Loser"),
                ],
                max_length=24,
            ),
        ),
    ]
