# Generated by Django 5.2.17 on 2026-09-22 18:07

import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddup', '0003_discard_loser_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DdupDiscoveryRun',
            fields=[
                ('id', nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('scanned_from', models.DateTimeField(blank=True, null=True)),
                ('members_considered', models.PositiveIntegerField(default=0)),
                ('tier1_created', models.PositiveIntegerField(default=0)),
                ('tier2_created', models.PositiveIntegerField(default=0)),
                ('tier3_created', models.PositiveIntegerField(default=0)),
                ('comparisons', models.PositiveBigIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(default='system', max_length=64)),
            ],
            options={
                'verbose_name': 'DDUP discovery run',
                'indexes': [models.Index(fields=['status', '-started_at'], name='ddup_ddupdi_status_3b9fd1_idx')],
            },
        ),
    ]
