# Generated by Django 5.2.14 on 2026-05-14 16:33

import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_id", models.CharField(db_index=True, max_length=64)),
                ("actor_kind", models.CharField(default="user", max_length=16)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("soft_delete", "Soft Delete"),
                            ("hard_delete", "Hard Delete"),
                            ("merge", "Merge"),
                            ("unmerge", "Unmerge"),
                            ("promote", "Promote"),
                            ("reject", "Reject"),
                        ],
                        max_length=24,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=64)),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("field_changes", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=256)),
                ("prev_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                ("self_hash", models.BinaryField(blank=True, max_length=32, null=True)),
            ],
            options={
                "verbose_name": "Audit event",
                "verbose_name_plural": "Audit events",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="security_au_entity__ba0add_idx",
                    ),
                    models.Index(
                        fields=["action", "occurred_at"],
                        name="security_au_action_d37bba_idx",
                    ),
                ],
            },
        ),
    ]
