# Generated by Django 5.2.14 on 2026-05-15 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_auditevent_chain_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_level",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("region", "Region"),
                            ("sub_region", "Sub Region"),
                            ("district", "District"),
                            ("sub_county", "Sub County"),
                            ("parish", "Parish"),
                            ("village", "Village"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope_code", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("granted_by", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator scope",
                "indexes": [
                    models.Index(
                        fields=["user", "active"], name="security_op_user_id_233ef9_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "scope_level", "scope_code"),
                        name="operator_scope_unique_per_user_level",
                    )
                ],
            },
        ),
    ]
