# Generated by Django 5.2.14 on 2026-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_operatorscope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorscope",
            name="scope_level",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("region", "Region"),
                    ("sub_region", "Sub Region"),
                    ("district", "District"),
                    ("sub_county", "Sub County"),
                    ("parish", "Parish"),
                    ("village", "Village"),
                    ("partner", "Partner"),
                ],
                max_length=16,
            ),
        ),
    ]
