# Generated by Django 5.2.14 on 2026-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0004_alter_operatorscope_scope_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("read", "Read"),
                    ("update", "Update"),
                    ("soft_delete", "Soft Delete"),
                    ("hard_delete", "Hard Delete"),
                    ("merge", "Merge"),
                    ("unmerge", "Unmerge"),
                    ("promote", "Promote"),
                    ("reject", "Reject"),
                ],
                max_length=64,
            ),
        ),
    ]
