# Generated by Django 5.2.17 on 2026-08-09 14:31

from django.db import migrations, models



def _sync_roles(apps, schema_editor):
    """Materialise the apps.security.roles catalogue as Django Groups.

    Additive: groups outside the catalogue are left alone. Removing a group
    removes access, and some may be created operationally, so that is never
    done implicitly.
    """
    from apps.security.roles import sync_groups
    sync_groups(apps)


def _unsync_roles(apps, schema_editor):
    """Drop only the permissions this migration created; leave the Groups.

    Deleting the Groups would strip role membership from real accounts, which
    is not something a `migrate` backwards should do silently.
    """
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(
        app_label="security", model="accesspolicy",
    ).first()
    if ct:
        Permission.objects.filter(content_type=ct).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_auditevent_action'),
        # _sync_roles reaches for Group / Permission / ContentType, and on a
        # fresh database (CI builds one per run) those apps must be migrated
        # first or the data step fails.
        ('auth', '__first__'),
        ('contenttypes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Access policy',
                'verbose_name_plural': 'Access policies',
                'permissions': [('data_view', 'Data View — read personal data within scope'), ('data_entry', 'Data Entry — create new records'), ('data_modify', 'Data Modifier — amend existing records'), ('data_delete', 'Data Deletion — soft-delete records'), ('data_approve', 'Data Approval — approve a change raised by someone else'), ('data_export', 'Data Export — generate an extract'), ('data_download', 'Data Download — retrieve a generated extract'), ('data_upload', 'Data Upload — bulk-import a dataset')],
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RunPython(_sync_roles, _unsync_roles),
    ]
