# Generated by Django 5.2.17 on 2026-08-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_access_policy_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorscope',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='After this moment the scope grants nothing. Blank = open-ended.', null=True),
        ),
    ]
