# Generated by Django 5.2.17 on 2026-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_operator_scope_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
