# Generated by Django 5.2.17 on 2026-08-10 13:28

from django.db import migrations, models



SEED_HEAD = """
-- Continue the existing chain rather than starting a second head.
INSERT INTO security_auditchainhead (id, last_hash, updated_at)
SELECT 1, (
    SELECT self_hash FROM security_auditevent
     ORDER BY occurred_at DESC, id DESC LIMIT 1
), now()
ON CONFLICT (id) DO NOTHING;
"""

INSTALL = """
CREATE OR REPLACE FUNCTION security_auditevent_chain_hash() RETURNS trigger AS $$
DECLARE
    latest_hash bytea;
    payload text;
BEGIN
    -- F6: take the tail from a single locked row instead of scanning the event
    -- table. Two concurrent inserts previously both read the same tail before
    -- either committed and both linked to it, forking the chain.
    --
    -- ON CONFLICT DO UPDATE rather than a plain SELECT ... FOR UPDATE so the
    -- row is recreated if it is missing (the test runner truncates it), while
    -- still locking it and RETURNING the current committed value. An advisory
    -- lock is NOT sufficient here: in READ COMMITTED a query inside a trigger
    -- uses the calling statement's snapshot, so a waiter would acquire the lock
    -- and still read a stale tail.
    INSERT INTO security_auditchainhead AS h (id, last_hash, updated_at)
         VALUES (1, NULL, now())
    ON CONFLICT (id) DO UPDATE SET id = 1
      RETURNING h.last_hash INTO latest_hash;

    NEW.prev_hash := latest_hash;

    payload := concat_ws(
        '|',
        NEW.id,
        NEW.occurred_at::text,
        NEW.actor_id,
        NEW.actor_kind,
        NEW.action,
        NEW.entity_type,
        NEW.entity_id,
        coalesce(NEW.field_changes::text, ''),
        coalesce(NEW.reason, ''),
        coalesce(host(NEW.ip_address), ''),
        coalesce(NEW.user_agent, '')
    );

    NEW.self_hash := digest(
        coalesce(NEW.prev_hash, ''::bytea) || convert_to(payload, 'UTF8'),
        'sha256'
    );

    UPDATE security_auditchainhead
       SET last_hash = NEW.self_hash, updated_at = now()
     WHERE id = 1;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

# Byte-for-byte the original payload; only the tail lookup differs. Changing
# the hashed columns would invalidate every existing self_hash.
REVERT = """
CREATE OR REPLACE FUNCTION security_auditevent_chain_hash() RETURNS trigger AS $$
DECLARE
    latest_hash bytea;
    payload text;
BEGIN
    SELECT self_hash INTO latest_hash
      FROM security_auditevent
     ORDER BY occurred_at DESC, id DESC
     LIMIT 1;

    NEW.prev_hash := latest_hash;

    payload := concat_ws(
        '|',
        NEW.id,
        NEW.occurred_at::text,
        NEW.actor_id,
        NEW.actor_kind,
        NEW.action,
        NEW.entity_type,
        NEW.entity_id,
        coalesce(NEW.field_changes::text, ''),
        coalesce(NEW.reason, ''),
        coalesce(host(NEW.ip_address), ''),
        coalesce(NEW.user_agent, '')
    );

    NEW.self_hash := digest(
        coalesce(NEW.prev_hash, ''::bytea) || convert_to(payload, 'UTF8'),
        'sha256'
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def _install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SEED_HEAD)
        schema_editor.execute(INSTALL)


def _uninstall(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERT)


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_audit_event_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainHead',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_hash', models.BinaryField(blank=True, max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit chain head',
                'verbose_name_plural': 'Audit chain head',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='audit_chain_head_singleton')],
            },
        ),
        migrations.RunPython(_install, _uninstall),
    ]
