# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("security", "0009_audit_chain_head")]

    operations = [
        migrations.AlterField(
            model_name="operatorscope",
            name="scope_level",
            field=models.CharField(
                choices=[
                    ("national", "National"), ("region", "Region"),
                    ("sub_region", "Sub Region"), ("district", "District"),
                    ("county", "County"), ("sub_county", "Sub County"),
                    ("parish", "Parish"), ("village", "Village"),
                    ("partner", "Partner"),
                ],
                max_length=16,
            ),
        ),
    ]
