# Generated by Django 5.2.14 on 2026-05-15 06:21

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Partner",
            },
        ),
        migrations.CreateModel(
            name="DataSharingAgreement",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("purpose", models.TextField(blank=True)),
                ("allowed_scopes", models.JSONField(default=dict)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("signed_by", models.CharField(blank=True, max_length=64)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements",
                        to="data_requests.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data sharing agreement",
            },
        ),
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("requester", models.CharField(max_length=64)),
                ("requester_note", models.TextField(blank=True)),
                ("request_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delivered", "Delivered"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approver", models.CharField(blank=True, max_length=64)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("manifest_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "row_count_delivered",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="data_requests.datasharingagreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data request",
                "indexes": [
                    models.Index(
                        fields=["dsa", "status"], name="data_reques_dsa_id_2caca7_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="data_reques_status_4d1ee0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="datasharingagreement",
            index=models.Index(
                fields=["partner", "status"], name="data_reques_partner_62a1fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasharingagreement",
            index=models.Index(
                fields=["status", "valid_to"], name="data_reques_status_ae1387_idx"
            ),
        ),
    ]
