# Generated by Django 5.2.14 on 2026-05-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_requests", "0002_lift_drs_dsas_to_partners_canonical"),
        ("partners", "0004_partnerusagedaily"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasharingagreement",
            name="partner",
        ),
        migrations.AlterField(
            model_name="datarequest",
            name="dsa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="partners.datasharingagreement",
            ),
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
        migrations.DeleteModel(
            name="DataSharingAgreement",
        ),
    ]
