# Generated by Django 5.2.14 on 2026-05-15 02:47

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_management", "0003_backfill_sub_region_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=64)),
                ("dsa_reference", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Programme",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("eligibility_rule_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("enrolled", "Enrolled"),
                            ("rejected", "Rejected"),
                            ("exited", "Exited"),
                        ],
                        default="sent",
                        max_length=24,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("programme_side_id", models.CharField(blank=True, max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("last_delivery_id", models.CharField(blank=True, max_length=64)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="data_management.household",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="referral.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
            },
        ),
        migrations.CreateModel(
            name="ProgrammeEnrolment",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("suspended", "Suspended"),
                            ("exited", "Exited"),
                        ],
                        max_length=24,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("exit_reason", models.CharField(blank=True, max_length=128)),
                ("payment_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="data_management.household",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="referral.programme",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="referral.referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme enrolment",
            },
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["programme", "status"], name="referral_re_program_ec58b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["household", "status"], name="referral_re_househo_95bd70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programmeenrolment",
            index=models.Index(
                fields=["programme", "household"], name="referral_pr_program_bc222a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programmeenrolment",
            index=models.Index(
                fields=["status", "effective_date"],
                name="referral_pr_status_9a05af_idx",
            ),
        ),
    ]
