# Generated by Django 5.2.14 on 2026-05-14 17:05

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Connector",
            },
        ),
        migrations.CreateModel(
            name="MappingRule",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromotionBatch",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("label", models.CharField(blank=True, max_length=128)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("approver_a", models.CharField(blank=True, max_length=64)),
                ("approver_b", models.CharField(blank=True, max_length=64)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("finalised_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ubos", "UBOS bulk"),
                            ("capi_walkin", "CAPI walk-in"),
                            ("web", "Web on-demand"),
                            ("kobo", "KoboToolbox"),
                            ("wfp_scope", "WFP SCOPE"),
                            ("odk", "ODK forms"),
                            ("partner_mis", "Partner programme MIS"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Source system",
            },
        ),
        migrations.CreateModel(
            name="ConnectorRun",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("records_received", models.PositiveIntegerField(default=0)),
                ("records_landed", models.PositiveIntegerField(default=0)),
                ("records_staged", models.PositiveIntegerField(default=0)),
                ("records_promoted", models.PositiveIntegerField(default=0)),
                ("records_quarantined", models.PositiveIntegerField(default=0)),
                ("records_rejected", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="ingestion_hub.connector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connector run",
            },
        ),
        migrations.CreateModel(
            name="MappingRuleVersion",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("version", models.PositiveIntegerField()),
                ("spec", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="ingestion_hub.mappingrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping rule version",
            },
        ),
        migrations.CreateModel(
            name="RawLanding",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("source_reference", models.CharField(blank=True, max_length=128)),
                (
                    "connector_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landings",
                        to="ingestion_hub.connectorrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw landing",
            },
        ),
        migrations.CreateModel(
            name="Quarantine",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("reason", models.CharField(max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("escalated", models.BooleanField(default=False)),
                (
                    "connector_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quarantine",
                        to="ingestion_hub.connectorrun",
                    ),
                ),
                (
                    "raw_landing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quarantine",
                        to="ingestion_hub.rawlanding",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mappingrule",
            name="source_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mapping_rules",
                to="ingestion_hub.sourcesystem",
            ),
        ),
        migrations.CreateModel(
            name="DataProvisionAgreement",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("purpose", models.TextField(blank=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("residence_policy_days", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dpas",
                        to="ingestion_hub.sourcesystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data provision agreement",
                "verbose_name_plural": "Data provision agreements",
            },
        ),
        migrations.AddField(
            model_name="connector",
            name="source_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connectors",
                to="ingestion_hub.sourcesystem",
            ),
        ),
        migrations.CreateModel(
            name="StageRecord",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "provisional_registry_id",
                    nsr_mis.common.fields.ULIDField(unique=True),
                ),
                ("canonical_payload", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("quality_failed", "Quality Failed"),
                            ("idv_pending", "Idv Pending"),
                            ("ddup_review", "Ddup Review"),
                            ("pending_promotion", "Pending Promotion"),
                            ("promoted", "Promoted"),
                            ("rejected", "Rejected"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="provisional",
                        max_length=24,
                    ),
                ),
                ("dqa_summary", models.JSONField(blank=True, default=dict)),
                ("ddup_candidates", models.JSONField(blank=True, default=list)),
                ("idv_outcome", models.CharField(blank=True, max_length=32)),
                ("promoted_household_id", models.CharField(blank=True, max_length=26)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_by", models.CharField(blank=True, max_length=64)),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_records",
                        to="ingestion_hub.connectorrun",
                    ),
                ),
                (
                    "mapping_rule_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_records",
                        to="ingestion_hub.mappingruleversion",
                    ),
                ),
                (
                    "raw_landing",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_record",
                        to="ingestion_hub.rawlanding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage record",
            },
        ),
        migrations.CreateModel(
            name="PromotionDecision",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("promote", "Promote"),
                            ("promote_as_merge", "Promote As Merge"),
                            ("reject", "Reject"),
                            ("hold", "Hold"),
                            ("auto_promote", "Auto Promote"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="ingestion_hub.promotionbatch",
                    ),
                ),
                (
                    "stage_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="ingestion_hub.stagerecord",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="connectorrun",
            index=models.Index(
                fields=["connector", "started_at"],
                name="ingestion_h_connect_315d1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connectorrun",
            index=models.Index(fields=["status"], name="ingestion_h_status_6d891f_idx"),
        ),
        migrations.AddConstraint(
            model_name="mappingruleversion",
            constraint=models.UniqueConstraint(
                fields=("rule", "version"), name="mapping_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="rawlanding",
            index=models.Index(
                fields=["connector_run", "received_at"],
                name="ingestion_h_connect_f9c26e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mappingrule",
            constraint=models.UniqueConstraint(
                fields=("source_system", "code"), name="mapping_rule_code_per_source"
            ),
        ),
        migrations.AddIndex(
            model_name="stagerecord",
            index=models.Index(
                fields=["state", "created_at"], name="ingestion_h_state_87b619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stagerecord",
            index=models.Index(
                fields=["connector_run"], name="ingestion_h_connect_1a3325_idx"
            ),
        ),
    ]
