# Generated by Django 5.2.14 on 2026-05-14 21:36

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion_hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastTrackAuditSample",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("household_id", models.CharField(max_length=26)),
                ("sampled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "stage_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fast_track_sample",
                        to="ingestion_hub.stagerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fast-track audit sample",
                "indexes": [
                    models.Index(
                        fields=["status", "sampled_at"],
                        name="ingestion_h_status_73a841_idx",
                    )
                ],
            },
        ),
    ]
