# Generated by Django 5.2.14 on 2026-05-15 16:38

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion_hub", "0002_fasttrackauditsample"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoboCredential",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "server_url",
                    models.URLField(
                        help_text="Kobo instance base URL, e.g. https://kobo.humanitarianresponse.info",
                        max_length=255,
                    ),
                ),
                ("token_encrypted", nsr_mis.common.fields.EncryptedBinaryField()),
                ("acquired_by_username", models.CharField(blank=True, max_length=128)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kobo credential",
            },
        ),
        migrations.AddField(
            model_name="connectorrun",
            name="run_type",
            field=models.CharField(
                choices=[("import", "Import"), ("test", "Test")],
                default="import",
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="connectorrun",
            index=models.Index(
                fields=["run_type", "started_at"], name="ingestion_h_run_typ_ceab3e_idx"
            ),
        ),
        migrations.AddField(
            model_name="kobocredential",
            name="source_system",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kobo_credential",
                to="ingestion_hub.sourcesystem",
            ),
        ),
    ]
