# Generated by Django 5.2.14 on 2026-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion_hub", "0004_seed_parish_walkin_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagerecord",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagerecord",
            name="last_edited_by",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
