# Generated by Django 5.2.17 on 2026-09-10 05:03

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion_hub', '0006_seed_nsr_unit_coordinator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesystem',
            name='kind',
            field=models.CharField(choices=[('ubos', 'UBOS bulk'), ('capi_walkin', 'CAPI walk-in'), ('web', 'Web on-demand'), ('kobo', 'KoboToolbox'), ('wfp_scope', 'WFP SCOPE'), ('odk', 'ODK forms'), ('partner_mis', 'Partner programme MIS'), ('nira', 'NIRA reverse-feed (vital events)')], max_length=24),
        ),
        migrations.CreateModel(
            name='NiraCredential',
            fields=[
                ('id', nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False)),
                ('webhook_secret_encrypted', nsr_mis.common.fields.EncryptedBinaryField()),
                ('configured_by_username', models.CharField(blank=True, max_length=128)),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nira_credential', to='ingestion_hub.sourcesystem')),
            ],
            options={
                'verbose_name': 'NIRA credential',
            },
        ),
        migrations.CreateModel(
            name='UbosCredential',
            fields=[
                ('id', nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False)),
                ('drop_path', models.CharField(help_text='Absolute directory on the DIH host where UBOS export files (.csv, .json, .jsonl) are dropped, each with a sibling <file>.sha256 checksum.', max_length=512)),
                ('require_checksum', models.BooleanField(default=True, help_text='Refuse to pull a file without a matching .sha256 sidecar (US-114: checksums verified before landing).')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubos_credential', to='ingestion_hub.sourcesystem')),
            ],
            options={
                'verbose_name': 'UBOS bulk credential',
            },
        ),
    ]
