# Generated by Django 5.2.14 on 2026-05-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeographicUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("region", "Region"),
                            ("sub_region", "Sub Region"),
                            ("district", "District"),
                            ("county", "County"),
                            ("sub_county", "Sub County"),
                            ("parish", "Parish"),
                            ("village", "Village"),
                        ],
                        max_length=16,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="reference_data.geographicunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic unit",
                "verbose_name_plural": "Geographic units",
                "indexes": [
                    models.Index(
                        fields=["level", "status"], name="reference_d_level_12d035_idx"
                    ),
                    models.Index(
                        fields=["parent"], name="reference_d_parent__74a2db_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "code", "effective_from"),
                        name="geounit_code_per_level_per_version",
                    )
                ],
            },
        ),
    ]
