# Generated by Django 5.2.14 on 2026-05-16 16:17

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceList",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("list_name", models.CharField(db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("author", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approval_note", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Choice list",
                "verbose_name_plural": "Choice lists",
                "indexes": [
                    models.Index(
                        fields=["status", "list_name"],
                        name="reference_d_status_b44dd0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("list_name", "version"),
                        name="choicelist_name_version_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChoiceOption",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=256)),
                ("language", models.CharField(default="en", max_length=8)),
                ("parent_code", models.CharField(blank=True, max_length=32)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deprecated", "Deprecated")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="reference_data.choicelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice option",
                "verbose_name_plural": "Choice options",
                "ordering": ("choice_list", "sort_order", "code"),
                "indexes": [
                    models.Index(
                        fields=["choice_list", "status"],
                        name="reference_d_choice__ce2949_idx",
                    ),
                    models.Index(
                        fields=["parent_code"], name="reference_d_parent__2488a3_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("choice_list", "code", "language"),
                        name="choiceoption_unique_per_list_lang",
                    )
                ],
            },
        ),
    ]
