# Generated by Django 5.2.14 on 2026-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0012_add_refrigerator_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="choicelist",
            name="is_pii_classified",
            field=models.BooleanField(default=False),
        ),
    ]
