# Generated by Django 5.2.14 on 2026-05-23 09:09
#
# Adds the two denormalised counters + the partial-unique constraint
# that enforces "at most one ACTIVE row per (level, code)". After
# adding the fields we walk the table once and backfill
# children_count_cached from the current parent FK graph.
# households_count_cached is left at zero — the nightly recompute
# task is the authoritative writer.

from django.db import migrations, models
from django.db.models import Count


def _backfill_children_counts(apps, schema_editor):
    GeographicUnit = apps.get_model("reference_data", "GeographicUnit")
    rows = (
        GeographicUnit.objects
        .values("parent_id")
        .annotate(c=Count("id"))
    )
    by_parent = {r["parent_id"]: r["c"] for r in rows if r["parent_id"]}
    for unit_id, count in by_parent.items():
        GeographicUnit.objects.filter(id=unit_id).update(
            children_count_cached=count,
        )


def _noop_reverse(apps, schema_editor):
    """Reverse — reset cached counts to zero. Idempotent."""
    GeographicUnit = apps.get_model("reference_data", "GeographicUnit")
    GeographicUnit.objects.update(children_count_cached=0)


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0013_choicelist_is_pii_classified"),
    ]

    operations = [
        migrations.AddField(
            model_name="geographicunit",
            name="children_count_cached",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="geographicunit",
            name="households_count_cached",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="geographicunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("level", "code"),
                name="geounit_one_active_per_code",
            ),
        ),
        migrations.RunPython(_backfill_children_counts, _noop_reverse),
    ]
