# Generated by Django 5.2.14 on 2026-06-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0016_update_programme_pmt_band_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicunit",
            name="code",
            field=models.CharField(max_length=48),
        ),
    ]
