# Generated by Django 5.2.17 on 2026-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0021_seed_legacy_deprecated_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'case-number sequence',
                'verbose_name_plural': 'case-number sequences',
                'ordering': ('prefix', '-year'),
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='refseq_unique_prefix_year')],
            },
        ),
    ]
