"""US-DATA-EXP-001 — Data Explorer initial schema.

Creates the catalogue tables (PrivacyClass, RefreshCadence, Dataset,
Variable, VariableApproval), the audit/observability tables
(AggregateQueryLog, QueryThrottleCounter, ExplorerSession,
CoverageSnapshot), and registers the matview-backed unmanaged models
(GrievancesSubcounty, HealthChronicSubregion, HouseholdBy*, etc.) so
the ORM knows about them. The CREATE MATERIALIZED VIEW DDL lives in
apps/data_management/migrations/0010_data_explorer_matviews.py — per
CLAUDE.md, raw SQL is allowed only inside data_management and
ingestion_hub.

Reversible: each CreateModel pairs with a DeleteModel on `migrate
data_explorer zero`. The matview rows survive because their DDL lives
in data_management.
"""

# Generated by Django 5.2.14 on 2026-05-27 22:20

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrievancesSubcounty",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("district_code", models.CharField(max_length=32)),
                ("sub_county_code", models.CharField(db_index=True, max_length=32)),
                ("category", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(blank=True, max_length=24)),
                ("grievance_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_grievances_subcounty",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HealthChronicSubregion",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("condition_code", models.CharField(blank=True, max_length=32)),
                ("member_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_health_chronic_subregion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HouseholdBySubcountyDemographics",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("district_code", models.CharField(max_length=32)),
                ("sub_county_code", models.CharField(db_index=True, max_length=32)),
                ("head_sex_code", models.CharField(blank=True, max_length=8)),
                ("head_age_band", models.CharField(blank=True, max_length=16)),
                ("household_count", models.PositiveIntegerField(default=0)),
                ("member_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_household_by_subcounty_demographics",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HouseholdBySubcountyPmt",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("district_code", models.CharField(max_length=32)),
                ("sub_county_code", models.CharField(db_index=True, max_length=32)),
                ("pmt_band", models.CharField(blank=True, max_length=24)),
                ("household_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_household_by_subcounty_pmt",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HouseholdShocksSubregion",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("shock_type", models.CharField(blank=True, max_length=32)),
                ("severity", models.CharField(blank=True, max_length=24)),
                ("household_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_household_shocks_subregion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MemberBySubcountyEducation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("district_code", models.CharField(max_length=32)),
                ("sub_county_code", models.CharField(db_index=True, max_length=32)),
                ("sex_code", models.CharField(blank=True, max_length=8)),
                ("age_band", models.CharField(blank=True, max_length=16)),
                ("attendance_status", models.CharField(blank=True, max_length=32)),
                ("member_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_member_by_subcounty_education",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MemberBySubcountyEmployment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("district_code", models.CharField(max_length=32)),
                ("sub_county_code", models.CharField(db_index=True, max_length=32)),
                ("sex_code", models.CharField(blank=True, max_length=8)),
                ("age_band", models.CharField(blank=True, max_length=16)),
                ("employment_status", models.CharField(blank=True, max_length=32)),
                ("member_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_member_by_subcounty_employment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralsSubcounty",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField()),
                ("sub_region_code", models.CharField(db_index=True, max_length=32)),
                ("district_code", models.CharField(max_length=32)),
                ("sub_county_code", models.CharField(db_index=True, max_length=32)),
                ("programme_code", models.CharField(blank=True, max_length=32)),
                ("referral_status", models.CharField(blank=True, max_length=24)),
                ("referral_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mv_explorer_referrals_subcounty",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RefreshCadence",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(
                        help_text="Nominal refresh period in seconds. Used by the staleness fallback (HTTP 503 when refreshed_at older than 2x this)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Refresh cadence",
                "verbose_name_plural": "Refresh cadences",
            },
        ),
        migrations.CreateModel(
            name="ExplorerSession",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("actor", models.CharField(db_index=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_query_at", models.DateTimeField(auto_now=True)),
                ("last_query_hash", models.CharField(blank=True, max_length=64)),
                (
                    "handoff_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("abandoned", "Abandoned"),
                            ("submitted", "Submitted to API-DRS"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("data_request_id", models.CharField(blank=True, max_length=26)),
                ("purpose_of_use", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Explorer session",
                "indexes": [
                    models.Index(
                        fields=["actor", "started_at"],
                        name="data_explor_actor_996b82_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivacyClass",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("personal", "Personal"),
                            ("sensitive", "Sensitive"),
                        ],
                        help_text="Canonical lookup key — public/internal/personal/sensitive.",
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "k_floor",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minimum cell count before suppression. 0 = no suppression (Public). Sensitive uses 0 too but is blocked at validation.",
                    ),
                ),
                (
                    "daily_user_cap",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-user-per-day aggregate query cap. NULL = unlimited (Public). 0 = blocked (Sensitive).",
                        null=True,
                    ),
                ),
                (
                    "daily_org_cap",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-org-per-day aggregate query cap. NULL = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "blocks_aggregate",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the aggregate endpoint refuses any query that touches a Variable in this class. Sensitive = True.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Privacy class",
                "verbose_name_plural": "Privacy classes",
                "indexes": [
                    models.Index(fields=["code"], name="data_explor_code_d62b66_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "source_matview",
                    models.CharField(
                        blank=True,
                        help_text="Postgres mv_explorer_* name backing this dataset. Blank during catalogue-only previews; required before aggregate queries can run.",
                        max_length=128,
                    ),
                ),
                (
                    "geographic_floor",
                    models.CharField(
                        default="sub_county",
                        help_text="One of region|sub_region|district|sub_county. Aggregate queries below this floor are refused with HTTP 422.",
                        max_length=24,
                    ),
                ),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("has_coverage_baseline", models.BooleanField(default=False)),
                ("has_synthetic_sample", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "privacy_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datasets",
                        to="data_explorer.privacyclass",
                    ),
                ),
                (
                    "refresh_cadence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datasets",
                        to="data_explorer.refreshcadence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
            },
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable dotted code e.g. 'household.dwelling_type'. Used in Query JSON projection + handoff payload.",
                        max_length=128,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_model",
                    models.CharField(
                        blank=True,
                        help_text="Django app_label.ModelName the field lives on.",
                        max_length=128,
                    ),
                ),
                ("source_field", models.CharField(blank=True, max_length=128)),
                (
                    "data_type",
                    models.CharField(
                        default="text",
                        help_text="One of text|number|boolean|date|select|geo. Drives the field-picker control and aggregation behaviour.",
                        max_length=24,
                    ),
                ),
                ("choice_list", models.CharField(blank=True, max_length=128)),
                ("choice_kind", models.CharField(blank=True, max_length=16)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive (pending approval)"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="inactive",
                        max_length=16,
                    ),
                ),
                ("questionnaire_section", models.CharField(blank=True, max_length=32)),
                ("has_completeness_baseline", models.BooleanField(default=False)),
                ("shape_hash", models.CharField(blank=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="data_explorer.dataset",
                    ),
                ),
                (
                    "privacy_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variables",
                        to="data_explorer.privacyclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable",
            },
        ),
        migrations.CreateModel(
            name="VariableApproval",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("approver", models.CharField(max_length=64)),
                (
                    "approval_role",
                    models.CharField(
                        choices=[
                            ("dqa", "DQA Approver"),
                            ("dpo", "Data Protection Officer"),
                        ],
                        max_length=8,
                    ),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "overridden_privacy_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides_granted",
                        to="data_explorer.privacyclass",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="data_explorer.variable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable approval",
            },
        ),
        migrations.CreateModel(
            name="CoverageSnapshot",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("geo_level", models.CharField(max_length=24)),
                ("geo_code", models.CharField(db_index=True, max_length=32)),
                ("geo_label", models.CharField(blank=True, max_length=128)),
                (
                    "completeness_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("captured_at", models.DateTimeField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_snapshots",
                        to="data_explorer.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage snapshot",
                "indexes": [
                    models.Index(
                        fields=["dataset", "geo_level"],
                        name="data_explor_dataset_9ebb2c_idx",
                    ),
                    models.Index(
                        fields=["dataset", "captured_at"],
                        name="data_explor_dataset_2327bd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AggregateQueryLog",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("actor", models.CharField(db_index=True, max_length=64)),
                ("executed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("projection_variables", models.JSONField(default=list)),
                ("filter_variables", models.JSONField(default=list)),
                ("filter_hash", models.CharField(db_index=True, max_length=64)),
                ("geographic_scope", models.JSONField(default=dict)),
                ("result_row_count", models.PositiveIntegerField(default=0)),
                ("suppressed_cell_count", models.PositiveIntegerField(default=0)),
                ("strictest_privacy_class", models.CharField(max_length=24)),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("matview_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("staleness_seconds", models.PositiveIntegerField(default=0)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="query_log",
                        to="data_explorer.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aggregate query log",
                "indexes": [
                    models.Index(
                        fields=["actor", "executed_at"],
                        name="data_explor_actor_2ddbd2_idx",
                    ),
                    models.Index(
                        fields=["dataset", "executed_at"],
                        name="data_explor_dataset_4e1bf7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QueryThrottleCounter",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("actor", models.CharField(max_length=64)),
                (
                    "org_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("date_utc", models.DateField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "privacy_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="throttle_counters",
                        to="data_explorer.privacyclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query throttle counter",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "privacy_class", "date_utc"),
                        name="data_explorer_throttle_unique_actor_class_day",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(fields=["code"], name="data_explor_code_1bec41_idx"),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["privacy_class"], name="data_explor_privacy_2514c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(fields=["status"], name="data_explor_status_a940de_idx"),
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(
                fields=["privacy_class"], name="data_explor_privacy_58b71b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(
                fields=["dataset", "status"], name="data_explor_dataset_0cefe6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.UniqueConstraint(
                fields=("dataset", "code"),
                name="data_explorer_variable_unique_dataset_code",
            ),
        ),
        migrations.AddIndex(
            model_name="variableapproval",
            index=models.Index(
                fields=["variable", "approval_role"],
                name="data_explor_variabl_7c8182_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="variableapproval",
            constraint=models.UniqueConstraint(
                fields=("variable", "approval_role"),
                name="data_explorer_variable_approval_unique_role",
            ),
        ),
    ]
