# Generated by Django 5.2.14 on 2026-05-15 08:05

import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NiraVerificationAttempt",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("nin_hash", models.BinaryField(max_length=32)),
                ("requester", models.CharField(default="system", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=256)),
                ("next_retry_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NIRA verification attempt",
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="identity_ve_status_8d1bc5_idx",
                    ),
                    models.Index(
                        fields=["nin_hash"], name="identity_ve_nin_has_16ddff_idx"
                    ),
                ],
            },
        ),
    ]
