# Generated by Django 5.2.14 on 2026-05-14 21:57

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMTModelVersion",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("variables", models.JSONField(default=list)),
                (
                    "intercept",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "validation_r_squared",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "band_cutoffs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"extreme_poverty": 0, "poverty": 30, "vulnerable": 60, "not_poor": 80}',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("author", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PMT model version",
                "indexes": [
                    models.Index(
                        fields=["status"], name="pmt_pmtmode_status_201de6_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PMTResult",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("score", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("extreme_poverty", "Extreme Poverty"),
                            ("poverty", "Poverty"),
                            ("vulnerable", "Vulnerable"),
                            ("not_poor", "Not Poor"),
                        ],
                        max_length=24,
                    ),
                ),
                ("inputs_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "triggered_by",
                    models.CharField(
                        default="manual",
                        help_text="dih_promote, upd_commit, manual, backfill",
                        max_length=32,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pmt_results",
                        to="data_management.household",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="pmt.pmtmodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMT result",
                "indexes": [
                    models.Index(
                        fields=["household", "-computed_at"],
                        name="pmt_pmtresu_househo_57c7bc_idx",
                    ),
                    models.Index(
                        fields=["model_version", "-computed_at"],
                        name="pmt_pmtresu_model_v_861f4a_idx",
                    ),
                ],
            },
        ),
    ]
