# Generated by Django 5.2.14 on 2026-05-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmt", "0004_seed_initial_band_thresholds"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pmtbandthreshold",
            new_name="pmt_pmtband_model_v_ebc7b5_idx",
            old_name="pmt_pmtband_model_v_b_band_n_idx",
        ),
        migrations.AddField(
            model_name="pmtmodelversion",
            name="band_strategy",
            field=models.CharField(
                default="threshold",
                help_text="Either 'threshold' (legacy fixed cutoffs read off band_cutoffs) or 'percentile' (daily-recomputed PMTBandThreshold rows). ADR-0024 sets percentile as the policy default once the band-threshold job has populated.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="pmtmodelversion",
            name="calibration_dataset",
            field=models.CharField(
                blank=True, help_text="e.g. 'UNHS 2023/24'.", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="pmtmodelversion",
            name="calibration_year_end",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Latest year of the calibration dataset. Used by the model-staleness check (recalibrate every 3 years per ADR-0023).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pmtmodelversion",
            name="band_cutoffs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"extreme_poverty": 0, "poverty": 30, ...} — score thresholds when band_strategy="threshold"; percentile ranks (0–100) when band_strategy="percentile" (defaults from MGLSD policy: {extreme_poverty: 10, poverty: 20, vulnerable: 30, not_poor: 100}).',
            ),
        ),
        migrations.AlterField(
            model_name="pmtresult",
            name="triggered_by",
            field=models.CharField(
                default="manual",
                help_text="ChoiceOption code from the seeded `pmt_trigger_source` ChoiceList (US-PMT-014). Canonical codes in apps.pmt.constants — do not hardcode.",
                max_length=32,
            ),
        ),
    ]
