# Generated by Django 5.2.14 on 2026-05-22 23:05

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmt", "0006_seed_pmt_v1_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMTModelSignOff",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("step", models.PositiveSmallIntegerField()),
                ("expected_role", models.CharField(max_length=64)),
                ("expected_email", models.CharField(blank=True, max_length=254)),
                ("actual_email", models.CharField(blank=True, max_length=254)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("audit_event_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signoffs",
                        to="pmt.pmtmodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMT model sign-off",
                "verbose_name_plural": "PMT model sign-offs",
                "ordering": ["model_version", "revision", "step"],
                "indexes": [
                    models.Index(
                        fields=["model_version", "revision"],
                        name="pmt_pmtmode_model_v_bc5902_idx",
                    ),
                    models.Index(
                        fields=["status"], name="pmt_pmtmode_status_064463_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_version", "revision", "step"),
                        name="pmt_signoff_step_unique",
                    )
                ],
            },
        ),
    ]
