# Generated by Django 5.2.14 on 2026-05-22 23:09

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmt", "0007_pmtmodelsignoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMTCoverageSnapshot",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("total_households", models.PositiveIntegerField(default=0)),
                ("scored", models.PositiveIntegerField(default=0)),
                ("scored_30d", models.PositiveIntegerField(default=0)),
                ("scored_90d", models.PositiveIntegerField(default=0)),
                ("stale_12mo", models.PositiveIntegerField(default=0)),
                ("taken_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "PMT coverage snapshot",
            },
        ),
        migrations.CreateModel(
            name="PMTRecomputeJobRun",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="ok", max_length=24)),
                ("rows_written", models.PositiveIntegerField(default=0)),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("actor", models.CharField(default="celery-beat", max_length=64)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "PMT recompute job run",
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="pmt_pmtreco_started_e295c0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PMTBandSnapshot",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("extreme_poverty", "Extreme Poverty"),
                            ("poverty", "Poverty"),
                            ("vulnerable", "Vulnerable"),
                            ("not_poor", "Not Poor"),
                        ],
                        max_length=24,
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("taken_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="band_snapshots",
                        to="pmt.pmtmodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMT band snapshot",
                "indexes": [
                    models.Index(
                        fields=["model_version", "-taken_at"],
                        name="pmt_pmtband_model_v_7cec04_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PMTSubregionSnapshot",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("sub_region_code", models.CharField(max_length=32)),
                ("sub_region_name", models.CharField(blank=True, max_length=128)),
                ("total_households", models.PositiveIntegerField(default=0)),
                ("scored_households", models.PositiveIntegerField(default=0)),
                ("in_poverty_count", models.PositiveIntegerField(default=0)),
                (
                    "poverty_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subregion_snapshots",
                        to="pmt.pmtmodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMT sub-region snapshot",
                "indexes": [
                    models.Index(
                        fields=["model_version", "-taken_at"],
                        name="pmt_pmtsubr_model_v_bdb935_idx",
                    ),
                    models.Index(
                        fields=["sub_region_code", "-taken_at"],
                        name="pmt_pmtsubr_sub_reg_6ea5d2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PMTVariableInfluence",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("variable_name", models.CharField(max_length=128)),
                ("weight", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "sample_mean",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "influence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variable_influences",
                        to="pmt.pmtmodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMT variable influence",
                "indexes": [
                    models.Index(
                        fields=["model_version", "-computed_at"],
                        name="pmt_pmtvari_model_v_b5f498_idx",
                    )
                ],
            },
        ),
    ]
