# Generated by Django 5.2.14 on 2026-05-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmt", "0008_dashboard_snapshot_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pmtmodelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
    ]
