# Generated by Django 5.2.14 on 2026-05-30 23:14

import django.db.models.deletion
import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_management", "0010_data_explorer_matviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentLanguage",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("label", models.CharField(max_length=64)),
                ("native_label", models.CharField(blank=True, max_length=64)),
                ("is_ready", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Consent language",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ConsentPurpose",
            fields=[
                ("author", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_note", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "lawful_basis",
                    models.CharField(
                        choices=[
                            ("CONSENT", "Consent"),
                            ("PUBLIC_TASK", "Public task"),
                            ("CONTRACT", "Contract"),
                            ("VITAL_INTEREST", "Vital interest"),
                            ("LEGAL_OBLIGATION", "Legal obligation"),
                            ("STATISTICAL_EXEMPTION", "Statistical exemption"),
                        ],
                        max_length=24,
                    ),
                ),
                ("withdrawable", models.BooleanField(default=True)),
                ("default_on", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_optional", models.BooleanField(default=True)),
                ("blurb", models.TextField(blank=True)),
                ("basis_note", models.TextField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent purpose",
                "ordering": ["display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["status", "code"], name="consent_con_status_10bcf1_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Granted"),
                            ("REFUSED", "Refused"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("PENDING_REVIEW", "Pending review"),
                            ("PENDING_RE_CONSENT", "Pending re-consent"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "captured_via",
                    models.CharField(
                        choices=[
                            ("WEB_INTAKE", "Web intake"),
                            ("CAPI", "CAPI"),
                            ("CITIZEN_PORTAL", "Citizen portal"),
                            ("DIH_FAST_TRACK", "DIH fast-track"),
                            ("LEGACY_BACKFILL", "Legacy backfill"),
                            ("UPD_RECAPTURE", "UPD re-capture"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "capture_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SIGNATURE", "Signature"),
                            ("THUMBPRINT", "Thumbprint"),
                            ("VERBAL_WITNESSED", "Verbal (witnessed)"),
                            ("DIGITAL", "Digital"),
                        ],
                        max_length=24,
                    ),
                ),
                ("captured_by", models.CharField(blank=True, max_length=64)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("proxy_member_id", models.CharField(blank=True, max_length=26)),
                ("proxy_relationship", models.CharField(blank=True, max_length=32)),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="data_management.member",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="consent.consentpurpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent record",
            },
        ),
        migrations.CreateModel(
            name="ConsentEvidence",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("SIGNATURE", "Signature image"),
                            ("THUMBPRINT", "Thumbprint image"),
                            ("WITNESS_STATEMENT", "Witness statement"),
                            ("DPA_DOCUMENT", "DPA document (fast-track)"),
                        ],
                        max_length=24,
                    ),
                ),
                ("object_key", models.CharField(blank=True, max_length=512)),
                ("thumbprint_sha256", models.CharField(blank=True, max_length=64)),
                ("witness_name", models.CharField(blank=True, max_length=128)),
                ("witness_role", models.CharField(blank=True, max_length=64)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consent_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="consent.consentrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent evidence",
                "ordering": ["consent_record", "-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentStatementVersion",
            fields=[
                ("author", models.CharField(max_length=64)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_note", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("text_i18n", models.JSONField(blank=True, default=dict)),
                ("placeholder_languages", models.JSONField(blank=True, default=list)),
                ("is_material", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statement_versions",
                        to="consent.consentpurpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent statement version",
                "ordering": ["purpose", "-version"],
            },
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="statement_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="consent.consentstatementversion",
            ),
        ),
        migrations.CreateModel(
            name="ConsentWithdrawalTicket",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_DPO_REVIEW", "In DPO review"),
                            ("CONFIRMED", "Confirmed"),
                            ("PUBLIC_TASK_OVERRIDE", "Public-task override"),
                            ("CLARIFICATION_REQUESTED", "Clarification requested"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("reason_note", models.TextField(blank=True)),
                ("requested_by", models.CharField(max_length=64)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("requested_at_day", models.DateField(db_index=True)),
                ("sla_deadline", models.DateTimeField()),
                (
                    "sla_breached_notified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sub_region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_tickets",
                        to="consent.consentrecord",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_withdrawal_tickets",
                        to="data_management.member",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_tickets",
                        to="consent.consentpurpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent withdrawal ticket",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalDecision",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("CONFIRM", "Confirm"),
                            ("OVERRIDE_PUBLIC_TASK", "Override (public task)"),
                            ("REQUEST_CLARIFICATION", "Request clarification"),
                            ("HOLD", "Hold"),
                        ],
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField()),
                ("decided_by", models.CharField(max_length=64)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("second_approver", models.CharField(blank=True, max_length=64)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="consent.consentwithdrawalticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal decision",
                "ordering": ["ticket", "-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecordVersion",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                ("member_id", models.CharField(db_index=True, max_length=26)),
                ("purpose_code", models.CharField(db_index=True, max_length=32)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Granted"),
                            ("REFUSED", "Refused"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("PENDING_REVIEW", "Pending review"),
                            ("PENDING_RE_CONSENT", "Pending re-consent"),
                        ],
                        max_length=24,
                    ),
                ),
                ("state_from", models.CharField(blank=True, max_length=24)),
                ("statement_version_id", models.CharField(blank=True, max_length=26)),
                ("captured_via", models.CharField(blank=True, max_length=24)),
                ("capture_method", models.CharField(blank=True, max_length=24)),
                ("captured_by", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=128)),
                (
                    "audit_event_id",
                    models.CharField(blank=True, db_index=True, max_length=26),
                ),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="consent.consentrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent record version",
                "ordering": ["consent_record", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["consent_record", "effective_from"],
                        name="consent_con_consent_b7be9a_idx",
                    ),
                    models.Index(
                        fields=["member_id", "purpose_code"],
                        name="consent_con_member__87a952_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="consentstatementversion",
            constraint=models.UniqueConstraint(
                fields=("purpose", "version"),
                name="consent_statement_purpose_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentstatementversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("purpose",),
                name="consent_statement_one_active_per_purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["member", "purpose"], name="consent_con_member__54baec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["purpose", "state"], name="consent_con_purpose_eb0d44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["sub_region_code", "id"], name="consent_con_sub_reg_940b67_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.UniqueConstraint(
                fields=("member", "purpose"),
                name="consent_record_unique_member_purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="consentwithdrawalticket",
            index=models.Index(
                fields=["state", "sla_deadline"], name="consent_con_state_d3037b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentwithdrawalticket",
            index=models.Index(
                fields=["sub_region_code", "state"],
                name="consent_con_sub_reg_bc7213_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentwithdrawalticket",
            constraint=models.UniqueConstraint(
                fields=("member", "purpose", "requested_at_day"),
                name="consent_withdrawal_idempotent_per_day",
            ),
        ),
    ]
