# Generated by Django 5.2.14 on 2026-05-14 21:53

import nsr_mis.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    nsr_mis.common.fields.ULIDField(primary_key=True, serialize=False),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("household", "Household"), ("member", "Member")],
                        max_length=16,
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=26)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("correction", "Correction"),
                            ("addition", "Addition"),
                            ("removal", "Removal"),
                            ("vital_event", "Vital Event"),
                            ("programme_state", "Programme State"),
                            ("recertification", "Recertification"),
                        ],
                        max_length=24,
                    ),
                ),
                ("pmt_relevant", models.BooleanField(default=False)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=list)),
                (
                    "source_channel",
                    models.CharField(
                        choices=[
                            ("parish", "Parish"),
                            ("capi", "Capi"),
                            ("web", "Web"),
                            ("nira", "Nira"),
                            ("partner_mis", "Partner Mis"),
                            ("citizen_portal", "Citizen Portal"),
                            ("grm", "Grm"),
                        ],
                        max_length=24,
                    ),
                ),
                ("requester", models.CharField(max_length=64)),
                ("requester_note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_approval", "Pending Approval"),
                            ("committed", "Committed"),
                            ("rejected", "Rejected"),
                            ("reversed", "Reversed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("required_role", models.CharField(blank=True, max_length=32)),
                ("approver", models.CharField(blank=True, max_length=64)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("pmt_preview", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Change request",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="update_work_entity__f49be5_idx",
                    ),
                    models.Index(
                        fields=["status", "sla_deadline"],
                        name="update_work_status_ab4f31_idx",
                    ),
                    models.Index(
                        fields=["change_type", "pmt_relevant"],
                        name="update_work_change__d3d3cf_idx",
                    ),
                ],
            },
        ),
    ]
