# Generated by Django 5.2.14 on 2026-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update_workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="sampled_for_audit",
            field=models.BooleanField(default=False),
        ),
    ]
