# Generated by Django 5.2.14 on 2026-05-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update_workflow", "0002_changerequest_sampled_for_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdRoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("correction", "Correction"),
                            ("addition", "Addition"),
                            ("removal", "Removal"),
                            ("vital_event", "Vital Event"),
                            ("programme_state", "Programme State"),
                            ("recertification", "Recertification"),
                        ],
                        max_length=24,
                    ),
                ),
                ("pmt_relevant", models.BooleanField()),
                ("required_role", models.CharField(max_length=32)),
                ("sla_hours", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "UPD routing rule",
                "verbose_name_plural": "UPD routing rules",
                "indexes": [
                    models.Index(
                        fields=["change_type", "pmt_relevant", "is_active"],
                        name="update_work_change__6c213c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("change_type", "pmt_relevant"),
                        name="upd_routing_unique_active_per_tuple",
                    )
                ],
            },
        ),
    ]
