# Generated by Django 5.2.14 on 2026-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update_workflow", "0004_seed_default_routing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("correction", "Correction"),
                    ("addition", "Addition"),
                    ("removal", "Removal"),
                    ("vital_event", "Vital Event"),
                    ("programme_state", "Programme State"),
                    ("recertification", "Recertification"),
                    ("life_event", "Life Event"),
                    ("verification", "Verification"),
                    ("address_move", "Address Move"),
                    ("roster_change", "Roster Change"),
                    ("asset_change", "Asset Change"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("household", "Household"),
                    ("member", "Member"),
                    ("all_members", "All Members"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="updroutingrule",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("correction", "Correction"),
                    ("addition", "Addition"),
                    ("removal", "Removal"),
                    ("vital_event", "Vital Event"),
                    ("programme_state", "Programme State"),
                    ("recertification", "Recertification"),
                    ("life_event", "Life Event"),
                    ("verification", "Verification"),
                    ("address_move", "Address Move"),
                    ("roster_change", "Roster Change"),
                    ("asset_change", "Asset Change"),
                ],
                max_length=24,
            ),
        ),
    ]
